"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

const ALL_LANGUAGES = [
  { code: "en", name: "English", dir: "ltr", flag: "🇬🇧" },
  { code: "tr", name: "Türkçe", dir: "ltr", flag: "🇹🇷" },
  { code: "ru", name: "Русский", dir: "ltr", flag: "🇷🇺" },
  { code: "fa", name: "فارسی", dir: "rtl", flag: "🇮🇷" },
  { code: "ar", name: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "de", name: "Deutsch", dir: "ltr", flag: "🇩🇪" },
];

const DICTIONARY = {
  en: {
    addToCart: "Add to Cart",
    addToOrder: "Add to Order",
    total: "Total",
    viewCart: "View Cart",
    empty: "No items found",
    currency: "₺",
    offers: "Offers",
    yourOrder: "Your Order",
    table: "Table",
    active: "Active",
    emptyCart: "Your cart is empty",
    newItems: "New Items (Not Sent)",
    remove: "Remove",
    sentToKitchen: "Sent to Kitchen",
    totalAmount: "Total Amount",
    confirmOrder: "Confirm Order",
    items: "Items",
    noNewItems: "No new items to order",
    showOnTable: "Show on Table",
    "3d": "3D",
    viewInAR: "View in AR",
    close: "Close",
    yourSelection: "Your Selection",
    readyToOrder: "Ready to Order",
    kitchenPreparing: "Kitchen Preparing",
    grandTotal: "Grand Total",
    yourBag: "Your Bag",
    emptyBag: "Empty Bag",
    qty: "Qty",
    checkout: "Checkout",
    exploreMenu: "Explore Menu",
    fineDining: "Fine Dining Experience",
    viewMenu: "View Menu",
    viewFullMenu: "View Full Menu",
    totalOrder: "Total Order",
    open: "Open",
    enterMenu: "Enter Menu",
    menuCategories: "Menu Categories",
    swipe: "Swipe",
    off: "OFF",
    // Cashier
    floorManager: "Floor Manager",
    editMode: "EDIT MODE",
    systemOnline: "System Online",
    offline: "Offline",
    occupied: "Occupied",
    addTable: "Add Table",
    woodParquet: "Wood Parquet",
    concrete: "Concrete",
    whiteMarble: "White Marble",
    terrazzo: "Terrazzo",
    black: "Black",
    resetSort: "Reset Sort",
    cancel: "Cancel",
    save: "Save",
    dragTables: "Drag tables to move",
    resizeTables: "Drag handles to resize",
    selectTargetTable: "Select Target Table",
    clickToMove: "Click any table to Move or Merge",
    transferCancelled: "Transfer cancelled",
    mergeSuccess: "Tables merged successfully!",
    moveSuccess: "Table moved successfully!",
    editFloor: "Edit Floor",
    // Analytics & Reports
    analytics: "Analytics",
    reports: "Reports",
    financialReports: "Financial & Security Reports",
    detailedBreakdown: "Detailed breakdown for",
    totalRevenue: "Total Revenue",
    totalDishOrdered: "Total Dish Ordered",
    totalCustomer: "Total Customer",
    grossSales: "Gross Sales",
    netCash: "Net Cash",
    netCard: "Net Card",
    voidedValue: "Voided Value",
    extraCharges: "Extra Charges",
    totalDiscounts: "Total Discounts",
    transactionalReport: "Transactional Report",
    productMix: "Product Mix",
    securityLog: "Security Log",
    today: "Today",
    week: "Week",
    month: "Month",
    threeMonths: "3 Months",
    year: "Year",
    // Waiter
    floorOverview: "Floor Overview",
    logout: "Logout",
    transferring: "Transferring",
    selectTargetTable: "Select Target Table",
    live: "Live",
    toConfirm: "To Confirm",
    noTables: "No tables found.",
    requests: "Requests",
    // Chef
    kitchenDisplay: "KITCHEN DISPLAY",
    activeTickets: "Active Tickets",
    allClear: "All clear, Chef!",
    noActiveOrders: "No active orders pending or preparing.",
    // Report Columns
    billId: "Bill ID",
    method: "Method",
    staff: "Staff",
    productName: "Product Name",
    quantitySold: "Quantity Sold",
    reason: "Reason",
    // Order Drawer
    closed: "Closed",
    add: "ADD",
    transferTable: "Transfer Table",
    closeTable: "Close Table",
    editingNote: "Editing Note",
    saving: "Saving...",
    tableNote: "Table Note",
    noNotes: "No notes added.",
    addNotePlaceholder: "Add a note for this table...",
    totalBill: "Total Bill",
    finishCheckout: "FINISH & CHECKOUT",
    processing: "PROCESSING...",
    tableEmpty: "Table is Empty",
    noActiveSession: "No active session found.",
    startSession: "START NEW SESSION",
    printBill: "Print Bill",
    newOrders: "New Orders (To Confirm)",
    newOrderCashier: "New Order (Cashier)",
    confirmSendCashier: "CONFIRM & SEND TO CASHIER",
    confirmSendKitchen: "CONFIRM & SEND TO KITCHEN",
    confirmServe: "CONFIRM & SERVE",
    sendKitchen: "SEND TO KITCHEN",
    markServed: "MARK AS SERVED",
    startPreparing: "START PREPARING",
    served: "Served",
    inKitchen: "In Kitchen / Preparing",
    updating: "UPDATING...",
    saveChanges: "Save Changes",
    edit: "Edit",
    readyForPrep: "Ready for Prep (Waiter Confirmed)",
    sentToKitchen: "Sent to Kitchen",
    callWaiter: "Call Waiter",
    requestBill: "Request Bill",
  },
  tr: {
    addToCart: "Sepete Ekle",
    addToOrder: "Siparişe Ekle",
    total: "Toplam",
    viewCart: "Sepeti Gör",
    empty: "Ürün bulunamadı",
    currency: "₺",
    offers: "Fırsatlar",
    yourOrder: "Siparişiniz",
    table: "Masa",
    active: "Aktif",
    emptyCart: "Sepetiniz boş",
    newItems: "Yeni Ürünler (Gönderilmedi)",
    remove: "Kaldır",
    sentToKitchen: "Mutfağa Gönderildi",
    totalAmount: "Toplam Tutar",
    confirmOrder: "Siparişi Onayla",
    items: "Ürün",
    noNewItems: "Yeni sipariş yok",
    showOnTable: "Masada Göster",
    "3d": "3D",
    viewInAR: "AR'da Görüntüle",
    close: "Kapat",
    yourSelection: "Seçimleriniz",
    readyToOrder: "Sipariş İçin Hazır",
    kitchenPreparing: "Mutfak Hazırlıyor",
    grandTotal: "Genel Toplam",
    yourBag: "Sepetiniz",
    emptyBag: "Boş Sepet",
    qty: "Adet",
    checkout: "Ödeme",
    exploreMenu: "Menüyü Keşfet",
    fineDining: "Özel Yemek Deneyimi",
    viewMenu: "Menüyü Gör",
    viewFullMenu: "Tüm Menüyü Gör",
    totalOrder: "Toplam Sipariş",
    open: "Açık",
    enterMenu: "Menüye Gir",
    menuCategories: "Menü Kategorileri",
    swipe: "Kaydır",
    off: "İNDİRİM",
    // Cashier
    floorManager: "Kat Yöneticisi",
    editMode: "DÜZENLEME MODU",
    systemOnline: "Sistem Çevrimiçi",
    offline: "Çevrimdışı",
    occupied: "Dolu",
    addTable: "Masa Ekle",
    woodParquet: "Ahşap Parke",
    concrete: "Beton",
    whiteMarble: "Beyaz Mermer",
    terrazzo: "Terrazzo",
    black: "Siyah",
    resetSort: "Sıralamayı Sıfırla",
    cancel: "İptal",
    save: "Kaydet",
    dragTables: "Masaları taşımak için sürükleyin",
    resizeTables: "Boyutlandırmak için tutamaçları sürükleyin",
    selectTargetTable: "Hedef Masayı Seçin",
    clickToMove: "Taşımak veya Birleştirmek için bir masaya tıklayın",
    transferCancelled: "Transfer iptal edildi",
    mergeSuccess: "Masalar başarıyla birleştirildi!",
    moveSuccess: "Masa başarıyla taşındı!",
    editFloor: "Katı Düzenle",
    // Analytics & Reports
    analytics: "Analitik",
    reports: "Raporlar",
    financialReports: "Finansal & Güvenlik Raporları",
    detailedBreakdown: "Detaylı döküm:",
    totalRevenue: "Toplam Gelir",
    totalDishOrdered: "Toplam Sipariş Edilen Yemek",
    totalCustomer: "Toplam Müşteri",
    grossSales: "Brüt Satış",
    netCash: "Net Nakit",
    netCard: "Net Kart",
    voidedValue: "İptal Tutarı",
    extraCharges: "Ekstra Ücretler",
    totalDiscounts: "Toplam İndirimler",
    transactionalReport: "İşlem Raporu",
    productMix: "Ürün Karışımı",
    securityLog: "Güvenlik Kaydı",
    today: "Bugün",
    week: "Hafta",
    month: "Ay",
    threeMonths: "3 Ay",
    year: "Yıl",
    // Waiter
    floorOverview: "Kat Görünümü",
    logout: "Çıkış",
    transferring: "Transfer Ediliyor",
    selectTargetTable: "Hedef Masayı Seç",
    live: "Canlı",
    toConfirm: "Onay Bekleyen",
    noTables: "Masa bulunamadı.",
    requests: "İstekler",
    // Chef
    kitchenDisplay: "MUTFAK EKRANI",
    activeTickets: "Aktif Fişler",
    allClear: "Her şey temiz, Şef!",
    noActiveOrders: "Bekleyen sipariş yok.",
    // Report Columns
    billId: "Fiş No",
    method: "Yöntem",
    staff: "Personel",
    productName: "Ürün Adı",
    quantitySold: "Satılan Adet",
    reason: "Sebep",
    // Order Drawer
    closed: "Kapalı",
    add: "EKLE",
    transferTable: "Masayı Taşı",
    closeTable: "Masayı Kapat",
    editingNote: "Notu Düzenle",
    saving: "Kaydediliyor...",
    tableNote: "Masa Notu",
    noNotes: "Not eklenmedi.",
    addNotePlaceholder: "Bu masa için not ekle...",
    totalBill: "Toplam Hesap",
    finishCheckout: "BİTİR & ÖDEME",
    processing: "İŞLENİYOR...",
    tableEmpty: "Masa Boş",
    noActiveSession: "Aktif oturum bulunamadı.",
    startSession: "YENİ OTURUM BAŞLAT",
    printBill: "Fiş Yazdır",
    newOrders: "Yeni Siparişler",
    newOrderCashier: "Yeni Sipariş (Kasiyer)",
    confirmSendCashier: "ONAYLA & KASİYERE GÖNDER",
    confirmSendKitchen: "ONAYLA & MUTFAĞA GÖNDER",
    confirmServe: "ONAYLA & SERVİS ET",
    sendKitchen: "MUTFAĞA GÖNDER",
    markServed: "SERVİS EDİLDİ OLARAK İŞARETLE",
    startPreparing: "HAZIRLAMAYA BAŞLA",
    served: "Servis Edildi",
    inKitchen: "Mutfakta / Hazırlanıyor",
    updating: "GÜNCELLENİYOR...",
    saveChanges: "Değişiklikleri Kaydet",
    edit: "Düzenle",
    readyForPrep: "Hazırlık İçin Hazır",
    sentToKitchen: "Mutfağa Gönderildi",
    callWaiter: "Garson Çağır",
    requestBill: "Hesap İste",
  },
  ru: {
    addToCart: "В корзину",
    addToOrder: "Добавить в заказ",
    total: "Итого",
    viewCart: "Корзина",
    empty: "Нет товаров",
    currency: "₺",
    offers: "Специальные",
    yourOrder: "Ваш заказ",
    table: "Стол",
    active: "Активен",
    emptyCart: "Корзина пуста",
    newItems: "Новые товары (Не отправлено)",
    remove: "Удалить",
    sentToKitchen: "Отправлено на кухню",
    totalAmount: "Общая сумма",
    confirmOrder: "Подтвердить заказ",
    items: "Товары",
    noNewItems: "Нет новых товаров",
    showOnTable: "Показать на столе",
    "3d": "3D",
    viewInAR: "Просмотр в AR",
    close: "Закрыть",
    yourSelection: "Ваш выбор",
    readyToOrder: "Готово к заказу",
    kitchenPreparing: "Кухня готовит",
    grandTotal: "Итого",
    yourBag: "Ваша корзина",
    emptyBag: "Пустая корзина",
    qty: "Кол-во",
    checkout: "Оформить",
    exploreMenu: "Изучить меню",
    fineDining: "Изысканная кухня",
    viewMenu: "Посмотреть меню",
    viewFullMenu: "Полное меню",
    totalOrder: "Общий заказ",
    open: "Открыто",
    enterMenu: "Войти в меню",
    menuCategories: "Категории",
    swipe: "Листайте",
    off: "СКИДКА",
    // Cashier
    floorManager: "Управление залом",
    editMode: "РЕЖИМ РЕДАКТИРОВАНИЯ",
    systemOnline: "Система онлайн",
    offline: "Офлайн",
    occupied: "Занято",
    addTable: "Добавить стол",
    woodParquet: "Паркет",
    concrete: "Бетон",
    whiteMarble: "Белый мрамор",
    terrazzo: "Терраццо",
    black: "Черный",
    resetSort: "Сбросить сорт.",
    cancel: "Отмена",
    save: "Сохранить",
    dragTables: "Перетащите столы",
    resizeTables: "Потяните за края для изменения",
    selectTargetTable: "Выберите целевой стол",
    clickToMove: "Нажмите на стол для перемещения",
    transferCancelled: "Перевод отменен",
    mergeSuccess: "Столы объединены!",
    moveSuccess: "Стол перемещен!",
    editFloor: "Редактировать зал",
    // Analytics & Reports
    analytics: "Аналитика",
    reports: "Отчеты",
    financialReports: "Финансовые отчеты",
    detailedBreakdown: "Подробный отчет за",
    totalRevenue: "Общая выручка",
    totalDishOrdered: "Всего блюд",
    totalCustomer: "Всего клиентов",
    grossSales: "Валовые продажи",
    netCash: "Наличные (Нетто)",
    netCard: "Карта (Нетто)",
    voidedValue: "Сумма отмен",
    extraCharges: "Доп. сборы",
    totalDiscounts: "Скидки",
    transactionalReport: "Отчет о транзакциях",
    productMix: "Ассортимент",
    securityLog: "Журнал безопасности",
    today: "Сегодня",
    week: "Неделя",
    month: "Месяц",
    threeMonths: "3 Месяца",
    year: "Год",
    // Waiter
    floorOverview: "Обзор зала",
    logout: "Выйти",
    transferring: "Перенос",
    selectTargetTable: "Выберите цель",
    live: "Онлайн",
    toConfirm: "Подтвердить",
    noTables: "Нет столов",
    requests: "Запросы",
    // Chef
    kitchenDisplay: "КУХОННЫЙ ЭКРАН",
    activeTickets: "Активные билеты",
    allClear: "Все чисто, Шеф!",
    noActiveOrders: "Нет активных заказов.",
    // Report Columns
    billId: "ID Чека",
    method: "Метод",
    staff: "Сотрудник",
    productName: "Название",
    quantitySold: "Продано",
    reason: "Причина",
    // Order Drawer
    closed: "Закрыто",
    add: "ДОБАВИТЬ",
    transferTable: "Перенести стол",
    closeTable: "Закрыть стол",
    editingNote: "Редактировать",
    saving: "Сохранение...",
    tableNote: "Заметка стола",
    noNotes: "Нет заметок.",
    addNotePlaceholder: "Добавить заметку...",
    totalBill: "Итоговый счет",
    finishCheckout: "ЗАВЕРШИТЬ И ОПЛАТИТЬ",
    processing: "ОБРАБОТКА...",
    tableEmpty: "Стол пуст",
    noActiveSession: "Нет активной сессии.",
    startSession: "НАЧАТЬ НОВУЮ СЕССИЮ",
    printBill: "Печать счета",
    newOrders: "Новые заказы",
    newOrderCashier: "Новый заказ (Касса)",
    confirmSendCashier: "ПОДТВЕРДИТЬ И ОТПРАВИТЬ НА КАССУ",
    confirmSendKitchen: "ПОДТВЕРДИТЬ И ОТПРАВИТЬ НА КУХНЮ",
    confirmServe: "ПОДТВЕРДИТЬ И ПОДАТЬ",
    sendKitchen: "ОТПРАВИТЬ НА КУХНЮ",
    markServed: "ОТМЕТИТЬ КАК ПОДАНО",
    startPreparing: "НАЧАТЬ ГОТОВКУ",
    served: "Подано",
    inKitchen: "На кухне / Готовится",
    updating: "ОБНОВЛЕНИЕ...",
    saveChanges: "Сохранить",
    edit: "Изменить",
    readyForPrep: "Готово к готовке",
    sentToKitchen: "Отправлено на кухню",
    callWaiter: "Позвать официанта",
    requestBill: "Попросить счет",
  },
  fa: {
    addToCart: "افزودن به سبد",
    addToOrder: "افزودن به سفارش",
    total: "جمع کل",
    viewCart: "مشاهده سبد",
    empty: "موردی یافت نشد",
    currency: "لیر",
    offers: "پیشنهادات",
    yourOrder: "سفارش شما",
    table: "میز",
    active: "فعال",
    emptyCart: "سبد خرید خالی است",
    newItems: "موارد جدید (ارسال نشده)",
    remove: "حذف",
    sentToKitchen: "به آشپزخانه ارسال شد",
    totalAmount: "مبلغ کل",
    confirmOrder: "تایید سفارش",
    items: "مورد",
    noNewItems: "مورد جدیدی برای سفارش نیست",
    showOnTable: "نمایش روی میز",
    "3d": "سه‌بعدی",
    viewInAR: "مشاهده در AR",
    close: "بستن",
    yourSelection: "انتخاب‌های شما",
    readyToOrder: "آماده سفارش",
    kitchenPreparing: "آشپزخانه در حال آماده‌سازی",
    grandTotal: "جمع کل",
    yourBag: "کیف شما",
    emptyBag: "کیف خالی",
    qty: "تعداد",
    checkout: "پرداخت",
    exploreMenu: "مشاهده منو",
    fineDining: "تجربه غذای عالی",
    viewMenu: "مشاهده منو",
    viewFullMenu: "مشاهده منوی کامل",
    totalOrder: "کل سفارش",
    open: "باز",
    enterMenu: "ورود به منو",
    menuCategories: "دسته‌بندی‌ها",
    swipe: "بکشید",
    off: "تخفیف",
    // Cashier
    floorManager: "مدیریت سالن",
    editMode: "حالت ویرایش",
    systemOnline: "سیستم آنلاین",
    offline: "آفلاین",
    occupied: "اشغال",
    addTable: "افزودن میز",
    woodParquet: "پارکت چوبی",
    concrete: "بتن",
    whiteMarble: "مرمر سفید",
    terrazzo: "ترازو",
    black: "مشکی",
    resetSort: "بازنشانی ترتیب",
    cancel: "لغو",
    save: "ذخیره",
    dragTables: "میزها را بکشید",
    resizeTables: "برای تغییر اندازه بکشید",
    selectTargetTable: "میز مقصد را انتخاب کنید",
    clickToMove: "برای انتقال یا ادغام روی میز کلیک کنید",
    transferCancelled: "انتقال لغو شد",
    mergeSuccess: "میزها با موفقیت ادغام شدند!",
    moveSuccess: "میز با موفقیت جابجا شد!",
    editFloor: "ویرایش سالن",
    // Analytics & Reports
    analytics: "آمار و تحلیل",
    reports: "گزارش‌ها",
    financialReports: "گزارش‌های مالی و امنیتی",
    detailedBreakdown: "جزئیات مربوط به",
    totalRevenue: "درآمد کل",
    totalDishOrdered: "کل غذاهای سفارش داده شده",
    totalCustomer: "تعداد مشتریان",
    grossSales: "فروش ناخالص",
    netCash: "خالص نقد",
    netCard: "خالص کارت",
    voidedValue: "مبلغ باطل شده",
    extraCharges: "هزینه‌های اضافی",
    totalDiscounts: "مجموع تخفیف‌ها",
    transactionalReport: "گزارش تراکنش‌ها",
    productMix: "ترکیب محصول",
    securityLog: "گزارش امنیتی",
    today: "امروز",
    week: "هفته",
    month: "ماه",
    threeMonths: "۳ ماه",
    year: "سال",
    // Waiter
    floorOverview: "نمای سالن",
    logout: "خروج",
    transferring: "در حال انتقال",
    selectTargetTable: "انتخاب میز مقصد",
    live: "زنده",
    toConfirm: "تایید نشده",
    noTables: "میزی پیدا نشد",
    requests: "درخواست‌ها",
    // Chef
    kitchenDisplay: "نمایشگر آشپزخانه",
    activeTickets: "تیکت‌های فعال",
    allClear: "همه چیز آماده است، سرآشپز!",
    noActiveOrders: "سفارش فعالی وجود ندارد.",
    // Report Columns
    billId: "شناسه صورتحساب",
    method: "روش",
    staff: "کارکنان",
    productName: "نام محصول",
    quantitySold: "تعداد فروخته شده",
    reason: "دلیل",
    // Order Drawer
    closed: "بسته",
    add: "افزودن",
    transferTable: "انتقال میز",
    closeTable: "بستن میز",
    editingNote: "ویرایش یادداشت",
    saving: "در حال ذخیره...",
    tableNote: "یادداشت میز",
    noNotes: "یادداشتی اضافه نشده.",
    addNotePlaceholder: "یادداشتی برای این میز بنویسید...",
    totalBill: "صورتحساب کل",
    finishCheckout: "اتمام و پرداخت",
    processing: "در حال پردازش...",
    tableEmpty: "میز خالی است",
    noActiveSession: "نشست فعالی یافت نشد.",
    startSession: "شروع نشست جدید",
    printBill: "چاپ صورتحساب",
    newOrders: "سفارشات جدید",
    newOrderCashier: "سفارش جدید (صندوقدار)",
    confirmSendCashier: "تایید و ارسال به صندوق",
    confirmSendKitchen: "تایید و ارسال به آشپزخانه",
    confirmServe: "تایید و سرو",
    sendKitchen: "ارسال به آشپزخانه",
    markServed: "علامت‌گذاری به عنوان سرو شده",
    startPreparing: "شروع آماده‌سازی",
    served: "سرو شده",
    inKitchen: "در آشپزخانه / در حال پخت",
    updating: "در حال بروزرسانی...",
    saveChanges: "ذخیره تغییرات",
    edit: "ویرایش",
    readyForPrep: "آماده برای پخت",
    sentToKitchen: "ارسال شده به آشپزخانه",
    callWaiter: "فراخوانی گارسون",
    requestBill: "درخواست صورتحساب",
  },
  ar: {
    addToCart: "أضف للسلة",
    addToOrder: "أضف للطلب",
    total: "المجموع",
    viewCart: "عرض السلة",
    empty: "لا يوجد عناصر",
    currency: "₺",
    offers: "عروض",
    yourOrder: "طلبك",
    table: "طاولة",
    active: "نشط",
    emptyCart: "سلتك فارغة",
    newItems: "عناصر جديدة (لم ترسل)",
    remove: "إزالة",
    sentToKitchen: "أرسل للمطبخ",
    totalAmount: "المبلغ الإجمالي",
    confirmOrder: "تأكيد الطلب",
    items: "عناصر",
    noNewItems: "لا توجد عناصر جديدة",
    showOnTable: "عرض على الطاولة",
    "3d": "ثلاثي الأبعاد",
    viewInAR: "عرض في AR",
    close: "إغلاق",
    yourSelection: "اختيارك",
    readyToOrder: "جاهز للطلب",
    kitchenPreparing: "المطبخ يحضر",
    grandTotal: "الإجمالي الكلي",
    yourBag: "حقيبتك",
    emptyBag: "حقيبة فارغة",
    qty: "الكمية",
    checkout: "الدفع",
    exploreMenu: "استكشف القائمة",
    fineDining: "تجربة طعام راقية",
    viewMenu: "عرض القائمة",
    viewFullMenu: "عرض القائمة الكاملة",
    totalOrder: "إجمالي الطلب",
    open: "مفتوح",
    enterMenu: "ادخل القائمة",
    menuCategories: "الفئات",
    swipe: "اسحب",
    off: "خصم",
    // Cashier
    floorManager: "مدير الصالة",
    editMode: "وضع التعديل",
    systemOnline: "النظام متصل",
    offline: "غير متصل",
    occupied: "مشغول",
    addTable: "إضافة طاولة",
    woodParquet: "باركيه خشبي",
    concrete: "خرسانة",
    whiteMarble: "رخام أبيض",
    terrazzo: "تيرازو",
    black: "أسود",
    resetSort: "إعادة تعيين الترتيب",
    cancel: "إلغاء",
    save: "حفظ",
    dragTables: "اسحب الطاولات للتحريك",
    resizeTables: "اسحب المقابض لتغيير الحجم",
    selectTargetTable: "اختر الطاولة المستهدفة",
    clickToMove: "انقر على أي طاولة للنقل أو الدمj",
    transferCancelled: "تم إلغاء النقل",
    mergeSuccess: "تم دمج الطاولات بنجاح!",
    moveSuccess: "تم نقل الطاولة بنجاح!",
    editFloor: "تعديل الصالة",
    // Analytics & Reports
    analytics: "تحليلات",
    reports: "تقارير",
    financialReports: "التقارير المالية والأمنية",
    detailedBreakdown: "تفاصيل لـ",
    totalRevenue: "إجمالي الإيرادات",
    totalDishOrdered: "إجمالي الأطباق المطلوبة",
    totalCustomer: "إجمالي العملاء",
    grossSales: "إجمالي المبيعات",
    netCash: "صافي النقد",
    netCard: "صافي البطاقة",
    voidedValue: "القيمة الملغاة",
    extraCharges: "رسوم إضافية",
    totalDiscounts: "إجمالي الخصومات",
    transactionalReport: "تقرير المعاملات",
    productMix: "مزيج المنتجات",
    securityLog: "سجل الأمان",
    today: "اليوم",
    week: "أسبوع",
    month: "شهر",
    threeMonths: "3 أشهر",
    year: "سنة",
    // Waiter
    floorOverview: "نظرة عامة",
    logout: "خروج",
    transferring: "جار النقل",
    selectTargetTable: "اختر الطاولة",
    live: "مباشر",
    toConfirm: "للتأكيد",
    noTables: "لا توجد طاولات",
    requests: "طلبات",
    // Chef
    kitchenDisplay: "شاشة المطبخ",
    activeTickets: "تذاكر نشطة",
    allClear: "كل شيء جاهز يا شيف!",
    noActiveOrders: "لا توجد طلبات نشطة.",
    // Report Columns
    billId: "رقم الفاتورة",
    method: "طريقة",
    staff: "الموظف",
    productName: "اسم المنتج",
    quantitySold: "الكمية المباعة",
    reason: "السبب",
    // Order Drawer
    closed: "مغلق",
    add: "إضافة",
    transferTable: "نقل الطاولة",
    closeTable: "إغلاق الطاولة",
    editingNote: "تعديل الملاحظة",
    saving: "جاري الحفظ...",
    tableNote: "ملاحظة الطاولة",
    noNotes: "لا توجد ملاحظات.",
    addNotePlaceholder: "أضف ملاحظة لهذه الطاولة...",
    totalBill: "إجمالي الفاتورة",
    finishCheckout: "إنهاء ودفع",
    processing: "جاري المعالجة...",
    tableEmpty: "الطاولة فارغة",
    noActiveSession: "لا توجد جلسة نشطة.",
    startSession: "بدء جلسة جديدة",
    printBill: "طباعة الفاتورة",
    newOrders: "طلبات جديدة",
    newOrderCashier: "طلب جديد (كاشير)",
    confirmSendCashier: "تأكيد وإرسال للكاشير",
    confirmSendKitchen: "تأكيد وإرسال للمطبخ",
    confirmServe: "تأكيد وتقديم",
    sendKitchen: "إرسال للمطبخ",
    markServed: "تحديد كمقدم",
    startPreparing: "بدء التحضير",
    served: "مقدم",
    inKitchen: "في المطبخ / جار التحضير",
    updating: "جاري التحديث...",
    saveChanges: "حفظ التغييرات",
    edit: "تعديل",
    readyForPrep: "جاهز للتحضير",
    sentToKitchen: "أرسل للمطبخ",
    callWaiter: "استدعاء النادل",
    requestBill: "طلب الفاتورة",
  },
  de: {
    addToCart: "In den Warenkorb",
    addToOrder: "Zur Bestellung",
    total: "Gesamt",
    viewCart: "Warenkorb",
    empty: "Keine Artikel",
    currency: "₺",
    offers: "Angebote",
    yourOrder: "Ihre Bestellung",
    table: "Tisch",
    active: "Aktiv",
    emptyCart: "Ihr Warenkorb ist leer",
    newItems: "Neue Artikel (Nicht gesendet)",
    remove: "Entfernen",
    sentToKitchen: "An Küche gesendet",
    totalAmount: "Gesamtbetrag",
    confirmOrder: "Bestellung bestätigen",
    items: "Artikel",
    noNewItems: "Keine neuen Artikel",
    showOnTable: "Auf Tisch zeigen",
    "3d": "3D",
    viewInAR: "In AR ansehen",
    close: "Schließen",
    yourSelection: "Ihre Auswahl",
    readyToOrder: "Bereit zur Bestellung",
    kitchenPreparing: "Küche bereitet vor",
    grandTotal: "Gesamtsumme",
    yourBag: "Ihre Tasche",
    emptyBag: "Leere Tasche",
    qty: "Menge",
    checkout: "Kasse",
    exploreMenu: "Menü erkunden",
    fineDining: "Gehobene Küche",
    viewMenu: "Menü ansehen",
    viewFullMenu: "Vollständiges Menü",
    totalOrder: "Gesamtbestellung",
    open: "Geöffnet",
    enterMenu: "Menü betreten",
    menuCategories: "Kategorien",
    swipe: "Wischen",
    off: "RABATT",
    // Cashier
    floorManager: "Saalmanager",
    editMode: "BEARBEITUNGSMODUS",
    systemOnline: "System Online",
    offline: "Offline",
    occupied: "Belegt",
    addTable: "Tisch hinzufügen",
    woodParquet: "Holzparkett",
    concrete: "Beton",
    whiteMarble: "Weißer Marmor",
    terrazzo: "Terrazzo",
    black: "Schwarz",
    resetSort: "Sortierung zurücksetzen",
    cancel: "Abbrechen",
    save: "Speichern",
    dragTables: "Tische zum Bewegen ziehen",
    resizeTables: "Griffe zum Ändern der Größe ziehen",
    selectTargetTable: "Zieltisch auswählen",
    clickToMove: "Klicken zum Verschieben/Zusammenführen",
    transferCancelled: "Übertragung abgebrochen",
    mergeSuccess: "Tische erfolgreich zusammengeführt!",
    moveSuccess: "Tisch erfolgreich verschoben!",
    editFloor: "Saal bearbeiten",
    // Analytics & Reports
    analytics: "Analytik",
    reports: "Berichte",
    financialReports: "Finanz- & Sicherheitsberichte",
    detailedBreakdown: "Detaillierte Aufschlüsselung für",
    totalRevenue: "Gesamtumsatz",
    totalDishOrdered: "Bestellte Gerichte",
    totalCustomer: "Gesamtkunden",
    grossSales: "Bruttoumsatz",
    netCash: "Netto Bar",
    netCard: "Netto Karte",
    voidedValue: "Stornierter Wert",
    extraCharges: "Zusatzgebühren",
    totalDiscounts: "Gesamtrabatte",
    transactionalReport: "Transaktionsbericht",
    productMix: "Produktmix",
    securityLog: "Sicherheitsprotokoll",
    today: "Heute",
    week: "Woche",
    month: "Monat",
    threeMonths: "3 Monate",
    year: "Jahr",
    // Waiter
    callWaiter: "Kellner rufen",
    requestBill: "Rechnung anfordern",
    floorOverview: "Saalübersicht",
    logout: "Abmelden",
    transferring: "Übertragen",
    selectTargetTable: "Zieltisch wählen",
    live: "Live",
    toConfirm: "Bestätigen",
    noTables: "Keine Tische",
    requests: "Anfragen",
    // Chef
    kitchenDisplay: "KÜCHENANZEIGE",
    activeTickets: "Aktive Tickets",
    allClear: "Alles erledigt, Chef!",
    noActiveOrders: "Keine aktiven Bestellungen.",
     // Report Columns
    billId: "Rechnungs-ID",
    method: "Methode",
    staff: "Personal",
    productName: "Produktname",
    quantitySold: "Verkaufte Menge",
    reason: "Grund",
    action: "Aktion",
    // Order Drawer
    closed: "Geschlossen",
    add: "HINZUFÜGEN",
    transferTable: "Tisch übertragen",
    closeTable: "Tisch schließen",
    editingNote: "Notiz bearbeiten",
    saving: "Speichern...",
    tableNote: "Tischnotiz",
    noNotes: "Keine Notizen hinzugefügt.",
    addNotePlaceholder: "Notiz für diesen Tisch hinzufügen...",
    totalBill: "Gesamtrechnung",
    finishCheckout: "FERTIGSTELLEN & KASSE",
    processing: "VERARBEITUNG...",
    tableEmpty: "Tisch ist leer",
    noActiveSession: "Keine aktive Sitzung gefunden.",
    startSession: "NEUE SITZUNG STARTEN",
    printBill: "Rechnung drucken",
    newOrders: "Neue Bestellungen",
    newOrderCashier: "Neue Bestellung (Kassierer)",
    confirmSendCashier: "BESTÄTIGEN & AN KASSIERER SENDEN",
    confirmSendKitchen: "BESTÄTIGEN & AN KÜCHE SENDEN",
    confirmServe: "BESTÄTIGEN & SERVIEREN",
    sendKitchen: "AN KÜCHE SENDEN",
    markServed: "ALS SERVIERT MARKIEREN",
    startPreparing: "ZUBEREITUNG STARTEN",
    served: "Serviert",
    inKitchen: "In Küche / Zubereitung",
    updating: "AKTUALISIEREN...",
    saveChanges: "Änderungen speichern",
    edit: "Bearbeiten",
    readyForPrep: "Bereit zur Zubereitung",
    sentToKitchen: "An Küche gesendet",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children, dbSettings }) => {
  const supportedCodes = dbSettings?.supported_languages || ALL_LANGUAGES.map(l => l.code);

  const availableLanguages = ALL_LANGUAGES.filter((lang) =>
    supportedCodes.includes(lang.code)
  );

  const [language, setLanguage] = useState(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("app-lang");
      if (saved && supportedCodes.includes(saved)) return saved;
    }
    return dbSettings?.default_language || "tr";
  });

  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
    localStorage.setItem("app-lang", language);

    const currentLangConfig = ALL_LANGUAGES.find((l) => l.code === language);
    const dir = currentLangConfig?.dir || "ltr";

    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) =>
    DICTIONARY[language]?.[key] || DICTIONARY["tr"][key] || key;

  const content = (data) => {
    if (!data) return "";
    return typeof data === "object"
      ? data[language] ||
          data[dbSettings?.default_language] ||
          data["tr"] ||
          Object.values(data)[0]
      : data;
  };

  if (!isLoaded) return null;

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        content,
        availableLanguages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
