"use client";
import React, { createContext, useContext, useState, useEffect } from "react";
import { useRestaurantData } from "@/app/hooks/useRestaurantData";

const ALL_LANGUAGES = [
  { code: "en", name: "English", dir: "ltr", flag: "🇬🇧" },
  { code: "tr", name: "Türkçe", dir: "ltr", flag: "🇹🇷" },
  { code: "ru", name: "Русский", dir: "ltr", flag: "🇷🇺" },
  { code: "fa", name: "فارسی", dir: "rtl", flag: "🇮🇷" },
  { code: "ar", name: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "de", name: "Deutsch", dir: "ltr", flag: "🇩🇪" },
];

const DICTIONARY = {
  en: {
    addToCart: "Add to Cart",
    addToOrder: "Add to Order",
    total: "Total",
    viewCart: "View Cart",
    empty: "No items found",
    currency: "₺",
    offers: "Offers",
    yourOrder: "Your Order",
    table: "Table",
    active: "Active",
    emptyCart: "Your cart is empty",
    newItems: "New Items (Not Sent)",
    remove: "Remove",
    sentToKitchen: "Sent to Kitchen",
    totalAmount: "Total Amount",
    confirmOrder: "Confirm Order",
    items: "Items",
    noNewItems: "No new items to order",
    showOnTable: "Show on Table",
    "3d": "3D",
    viewInAR: "View in AR",
    close: "Close",
    yourSelection: "Your Selection",
    readyToOrder: "Ready to Order",
    kitchenPreparing: "Kitchen Preparing",
    grandTotal: "Grand Total",
    yourBag: "Your Bag",
    emptyBag: "Empty Bag",
    qty: "Qty",
    checkout: "Checkout",
    exploreMenu: "Explore Menu",
    fineDining: "Fine Dining Experience",
    viewMenu: "View Menu",
    viewFullMenu: "View Full Menu",
    totalOrder: "Total Order",
    open: "Open",
    enterMenu: "Enter Menu",
    menuCategories: "Menu Categories",
    swipe: "Swipe",
    off: "OFF",
    // Cashier
    swipeToDelete: "Swipe to Delete",
    floorManager: "Floor Manager",
    editMode: "EDIT MODE",
    systemOnline: "System Online",
    offline: "Offline",
    occupied: "Occupied",
    addTable: "Add Table",
    woodParquet: "Wood Parquet",
    concrete: "Concrete",
    whiteMarble: "White Marble",
    terrazzo: "Terrazzo",
    black: "Black",
    resetSort: "Reset Sort",
    cancel: "Cancel",
    save: "Save",
    dragTables: "Drag tables to move",
    resizeTables: "Drag handles to resize",
    selectTargetTable: "Select Target Table",
    clickToMove: "Click any table to Move or Merge",
    transferCancelled: "Transfer cancelled",
    mergeSuccess: "Tables merged successfully!",
    moveSuccess: "Table moved successfully!",
    editFloor: "Edit Floor",
    // Analytics & Reports
    analytics: "Analytics",
    reports: "Reports",
    financialReports: "Financial & Security Reports",
    detailedBreakdown: "Detailed breakdown for",
    totalRevenue: "Total Revenue",
    totalDishOrdered: "Total Dish Ordered",
    totalCustomer: "Total Customer",
    grossSales: "Gross Sales",
    netCash: "Net Cash",
    netCard: "Net Card",
    voidedValue: "Voided Value",
    extraCharges: "Extra Charges",
    totalDiscounts: "Total Discounts",
    transactionalReport: "Transactional Report",
    productMix: "Product Mix",
    securityLog: "Security Log",
    today: "Today",
    week: "Week",
    month: "Month",
    threeMonths: "3 Months",
    year: "Year",
    // Waiter
    floorOverview: "Floor Overview",
    logout: "Logout",
    transferring: "Transferring",
    selectTargetTable: "Select Target Table",
    live: "Live",
    toConfirm: "To Confirm",
    noTables: "No tables found.",
    requests: "Requests",
    // Chef
    kitchenDisplay: "KITCHEN DISPLAY",
    activeTickets: "Active Tickets",
    allClear: "All clear, Chef!",
    noActiveOrders: "No active orders pending or preparing.",
    // Report Columns
    billId: "Bill ID",
    method: "Method",
    staff: "Staff",
    productName: "Product Name",
    quantitySold: "Quantity Sold",
    reason: "Reason",
    // Order Drawer
    closed: "Closed",
    add: "ADD",
    transferTable: "Transfer Table",
    closeTable: "Close Table",
    editingNote: "Editing Note",
    saving: "Saving...",
    tableNote: "Table Note",
    noNotes: "No notes added.",
    addNotePlaceholder: "Add a note for this table...",
    totalBill: "Total Bill",
    finishCheckout: "FINISH & CHECKOUT",
    processing: "PROCESSING...",
    tableEmpty: "Table is Empty",
    noActiveSession: "No active session found.",
    startSession: "START NEW SESSION",
    printBill: "Print Bill",
    newOrders: "New Orders (To Confirm)",
    newOrderCashier: "New Order (Cashier)",
    confirmSendCashier: "CONFIRM & SEND TO CASHIER",
    confirmSendKitchen: "CONFIRM & SEND TO KITCHEN",
    confirmServe: "CONFIRM & SERVE",
    sendKitchen: "SEND TO KITCHEN",
    markServed: "MARK AS SERVED",
    startPreparing: "START PREPARING",
    served: "Served",
    inKitchen: "In Kitchen / Preparing",
    updating: "UPDATING...",
    saveChanges: "Save Changes",
    edit: "Edit",
    readyForPrep: "Ready for Prep (Waiter Confirmed)",
    sentToKitchen: "Sent to Kitchen",
    callWaiter: "Call Waiter",
    requestBill: "Request Bill",
    // Transaction Modal
    transactionDetails: "Transaction Details",
    id: "ID",
    loadingDetails: "Loading details...",
    failedToLoadDetails: "Failed to load details.",
    itemsInSession: "Items in Session",
    partialPayment: "Partial Payment",
    noItemsFound: "No items found.",
    noImg: "No Img",
    billAdjustments: "Bill Adjustments",
    itemsTotal: "Items Total",
    billTotal: "Bill Total",
    paidThisTransaction: "Paid (This Transaction)",
    totalPaid: "Total Paid",
    qtyLabel: "Qty",
    sessionNote: "Session Note",
    // Reports & Dashboard
    hourlyTraffic: "Hourly Traffic",
    salesByCategory: "Sales by Category",
    mostOrdered: "Most Ordered",
    viewAll: "View All",
    viewLess: "View Less",
    smartSort: "Smart Sort",
    numericSort: "123 Sort",
    kitchenStatus: "Kitchen",
    orders: "Orders",
    peakHours: "Peak Hours",
    dishesOrdered: "dishes ordered",
    today: "Today",
    // Toasts & Alerts
    menuLoadFailed: "Menu load failed",
    addedToOrder: "Added to Order",
    removedFromOrder: "Removed from Order",
    nothingToSend: "Nothing to send",
    sentToKitchen: "Sent to Kitchen! 👨‍🍳",
    sentToCashier: "Sent to Cashier for Approval! ⏳",
    ordersServed: "Orders Served! ✅",
    orderUpdated: "Order Updated",
    tableStarted: "Table Started! 🟢",
    tableClosed: "Table Closed",
    tableClosedVoided: "Table Closed & Orders Voided",
    itemVoided: "Item Voided",
    failedToConfirm: "Failed to confirm",
    failedToSend: "Failed to send",
    failedToUpdate: "Failed to update",
    failedToDelete: "Failed to delete",
    checkoutFailed: "Checkout Failed",
    somethingWentWrong: "Something went wrong.",
    requestSent: "Request Sent!",
    billSent: "Bill Request Sent!",
    waiterSent: "Waiter Call Sent!",
    failedToStart: "Failed to start",
    // Waiter & Statuses
    activeTables: "Active Tables",
    floorOverview: "Overview",
    logoutConfirm: "Are you sure you want to logout?",
    transferring: "Transferring",
    selectTargetTable: "Select Target Table",
    clickToMove: "Click a table to move/merge",
    transferCancelled: "Transfer cancelled",
    mergeSuccess: "Table merged successfully",
    moveSuccess: "Table moved successfully",
    cannotTransferSelf: "Cannot transfer to self!",
    sourceNoSession: "Source table has no active session!",
    mergeFailed: "Merge failed",
    moveFailed: "Move failed",
    requestCleared: "Request Cleared",
    loadingFloor: "LOADING FLOOR...",
    waiterDisabled: "Waiter App Disabled",
    moduleOff: "This module is currently turned off.",
    // Table Status Labels
    statusEmpty: "Empty",
    statusSeated: "Seated",
    statusDining: "Dining",
    statusCooking: "COOKING",
    statusWaiting: "WAITING",
    statusNewOrder: "NEW ORDER",
    statusKitchenSent: "KITCHEN SENT",
    statusBillRequest: "BILL REQUEST",
    statusCalling: "CALLING!",
    statusAlert: "ALERT",
    statusMergeHere: "MERGE HERE",
    statusMoveHere: "MOVE HERE",
    statusSource: "Source",
    orderNote: "Order Note",
    notePlaceholder: "Allergies, extra spicy, etc...",
    // Payment Modal
    sendToKitchen: "Send to Kitchen",
    itemsSelected: "items selected",
    people: "People",
    payNow: "Amount to Pay Now",
    allPrepared: "ALL PREPARED",
    selectPaymentMethod: "Select Payment Method",
    cash: "CASH",
    card: "CARD",
    mixed: "MIXED",
    cashPortion: "Cash Portion",
    cardPortion: "Card Portion",
    autofill: "Autofill Remainder",
    confirmPayment: "Confirm Payment",
    paymentRecorded: "Payment Recorded",
    paymentFailed: "Payment Failed",
    mixedMismatch: "Mixed amounts must equal Amount to Pay",
    invalidAmount: "Invalid Payment Amount",
    amountExceeds: "Amount exceeds remaining due",
    splitMode: "Split Mode",
    byPeople: "By People",
    byItems: "By Items",
    custom: "Custom",
    splitCount: "Split Count",
    selectItemsHint: "Select items from the list on the left to calculate total.",
    fullPayment: "FULL PAYMENT",
    splitPayment: "SPLIT / PARTIAL",
    adjustments: "Adjustments",
    addAdjustment: "Add Discount / Charge",
    addAdjTitle: "Add Adjustment",
    extraCharge: "Extra Charge",
    discount: "Discount",
    description: "Description",
    descPlaceholder: "e.g. Service Fee",
    amountLabel: "Amount",
    applyAdjustment: "Apply Adjustment",
    paid: "Paid",
    remainingDue: "Remaining Due",
    orderDetails: "Order Details",
    fillAllFields: "Please fill all fields",
    adjAdded: "Adjustment Added",
  },
  tr: {
    addToCart: "Sepete Ekle",
    addToOrder: "Siparişe Ekle",
    total: "Toplam",
    viewCart: "Sepeti Gör",
    empty: "Ürün bulunamadı",
    currency: "₺",
    offers: "Fırsatlar",
    yourOrder: "Siparişiniz",
    table: "Masa",
    active: "Aktif",
    emptyCart: "Sepetiniz boş",
    newItems: "Yeni Ürünler (Gönderilmedi)",
    remove: "Kaldır",
    sentToKitchen: "Mutfağa Gönderildi",
    totalAmount: "Toplam Tutar",
    confirmOrder: "Siparişi Onayla",
    items: "Ürün",
    noNewItems: "Yeni sipariş yok",
    showOnTable: "Masada Göster",
    "3d": "3D",
    viewInAR: "AR'da Görüntüle",
    close: "Kapat",
    yourSelection: "Seçimleriniz",
    readyToOrder: "Sipariş İçin Hazır",
    kitchenPreparing: "Mutfak Hazırlıyor",
    grandTotal: "Genel Toplam",
    yourBag: "Sepetiniz",
    emptyBag: "Boş Sepet",
    qty: "Adet",
    checkout: "Ödeme",
    exploreMenu: "Menüyü Keşfet",
    fineDining: "Özel Yemek Deneyimi",
    viewMenu: "Menüyü Gör",
    viewFullMenu: "Tüm Menüyü Gör",
    totalOrder: "Toplam Sipariş",
    open: "Açık",
    enterMenu: "Menüye Gir",
    menuCategories: "Menü Kategorileri",
    swipe: "Kaydır",
    off: "İNDİRİM",
    // Cashier
    swipeToDelete: "Silmek için Kaydır",
    floorManager: "Kat Yöneticisi",
    editMode: "DÜZENLEME MODU",
    systemOnline: "Sistem Çevrimiçi",
    offline: "Çevrimdışı",
    occupied: "Dolu",
    addTable: "Masa Ekle",
    woodParquet: "Ahşap Parke",
    concrete: "Beton",
    whiteMarble: "Beyaz Mermer",
    terrazzo: "Terrazzo",
    black: "Siyah",
    resetSort: "Sıralamayı Sıfırla",
    cancel: "İptal",
    save: "Kaydet",
    dragTables: "Masaları taşımak için sürükleyin",
    resizeTables: "Boyutlandırmak için tutamaçları sürükleyin",
    selectTargetTable: "Hedef Masayı Seçin",
    clickToMove: "Taşımak veya Birleştirmek için bir masaya tıklayın",
    transferCancelled: "Transfer iptal edildi",
    mergeSuccess: "Masalar başarıyla birleştirildi!",
    moveSuccess: "Masa başarıyla taşındı!",
    editFloor: "Katı Düzenle",
    // Analytics & Reports
    analytics: "Analitik",
    reports: "Raporlar",
    financialReports: "Finansal & Güvenlik Raporları",
    detailedBreakdown: "Detaylı döküm:",
    totalRevenue: "Toplam Gelir",
    totalDishOrdered: "Toplam Sipariş Edilen Yemek",
    totalCustomer: "Toplam Müşteri",
    grossSales: "Brüt Satış",
    netCash: "Net Nakit",
    netCard: "Net Kart",
    voidedValue: "İptal Tutarı",
    extraCharges: "Ekstra Ücretler",
    totalDiscounts: "Toplam İndirimler",
    transactionalReport: "İşlem Raporu",
    productMix: "Ürün Karışımı",
    securityLog: "Güvenlik Kaydı",
    today: "Bugün",
    week: "Hafta",
    month: "Ay",
    threeMonths: "3 Ay",
    year: "Yıl",
    // Waiter
    floorOverview: "Kat Görünümü",
    logout: "Çıkış",
    transferring: "Transfer Ediliyor",
    selectTargetTable: "Hedef Masayı Seç",
    live: "Canlı",
    toConfirm: "Onay Bekleyen",
    noTables: "Masa bulunamadı.",
    requests: "İstekler",
    // Chef
    kitchenDisplay: "MUTFAK EKRANI",
    activeTickets: "Aktif Fişler",
    allClear: "Her şey temiz, Şef!",
    noActiveOrders: "Bekleyen sipariş yok.",
    // Report Columns
    billId: "Fiş No",
    method: "Yöntem",
    staff: "Personel",
    productName: "Ürün Adı",
    quantitySold: "Satılan Adet",
    reason: "Sebep",
    // Order Drawer
    closed: "Kapalı",
    add: "EKLE",
    transferTable: "Masayı Taşı",
    closeTable: "Masayı Kapat",
    editingNote: "Notu Düzenle",
    saving: "Kaydediliyor...",
    tableNote: "Masa Notu",
    noNotes: "Not eklenmedi.",
    addNotePlaceholder: "Bu masa için not ekle...",
    totalBill: "Toplam Hesap",
    finishCheckout: "BİTİR & ÖDEME",
    processing: "İŞLENİYOR...",
    tableEmpty: "Masa Boş",
    noActiveSession: "Aktif oturum bulunamadı.",
    startSession: "YENİ OTURUM BAŞLAT",
    printBill: "Fiş Yazdır",
    newOrders: "Yeni Siparişler",
    newOrderCashier: "Yeni Sipariş (Kasiyer)",
    confirmSendCashier: "ONAYLA & KASİYERE GÖNDER",
    confirmSendKitchen: "ONAYLA & MUTFAĞA GÖNDER",
    confirmServe: "ONAYLA & SERVİS ET",
    sendKitchen: "MUTFAĞA GÖNDER",
    markServed: "SERVİS EDİLDİ OLARAK İŞARETLE",
    startPreparing: "HAZIRLAMAYA BAŞLA",
    served: "Servis Edildi",
    inKitchen: "Mutfakta / Hazırlanıyor",
    updating: "GÜNCELLENİYOR...",
    saveChanges: "Değişiklikleri Kaydet",
    edit: "Düzenle",
    readyForPrep: "Hazırlık İçin Hazır",
    sentToKitchen: "Mutfağa Gönderildi",
    callWaiter: "Garson Çağır",
    requestBill: "Hesap İste",
    // Transaction Modal
    transactionDetails: "İşlem Detayları",
    id: "ID",
    loadingDetails: "Detaylar yükleniyor...",
    failedToLoadDetails: "Detaylar yüklenemedi.",
    itemsInSession: "Oturumdaki Ürünler",
    partialPayment: "Kısmi Ödeme",
    noItemsFound: "Ürün bulunamadı.",
    noImg: "Resimsiz",
    billAdjustments: "Fiş Düzeltmeleri",
    itemsTotal: "Ürün Toplamı",
    billTotal: "Fiş Toplamı",
    paidThisTransaction: "Ödenen (Bu İşlem)",
    totalPaid: "Toplam Ödenen",
    qtyLabel: "Adet",
    sessionNote: "Oturum Notu",
    // Reports & Dashboard
    hourlyTraffic: "Saatlik Trafik",
    salesByCategory: "Kategori Satışları",
    mostOrdered: "En Çok Sipariş Edilen",
    viewAll: "Tümünü Gör",
    viewLess: "Daha Az Gör",
    smartSort: "Akıllı Sırala",
    numericSort: "123 Sırala",
    kitchenStatus: "Mutfak",
    orders: "Siparişler",
    peakHours: "Yoğun Saatler",
    dishesOrdered: "sipariş edilen yemekler",
    today: "Bugün",
    orderNote: "Sipariş Notu",
    notePlaceholder: "Alerjiler, ekstra acı vb...",
    // Payment Modal
    sendToKitchen: "Mutfağa Gönder",
    itemsSelected: "ürün seçildi",
    people: "Kişi",
    payNow: "Ödenecek Tutar",
    allPrepared: "HEPSİ HAZIR",
    selectPaymentMethod: "Ödeme Yöntemini Seçin",
    cash: "NAKİT",
    card: "KART",
    mixed: "KARIŞIK",
    cashPortion: "Nakit Kısmı",
    cardPortion: "Kart Kısmı",
    autofill: "Kalanı Doldur",
    confirmPayment: "Ödemeyi Onayla",
    paymentRecorded: "Ödeme Kaydedildi",
    paymentFailed: "Ödeme Başarısız",
    mixedMismatch: "Karışık tutarlar Ödenecek Tutara eşit olmalıdır",
    invalidAmount: "Geçersiz Ödeme Tutarı",
    amountExceeds: "Tutar kalanı aşıyor",
    splitMode: "Bölme Modu",
    byPeople: "Kişi Başı",
    byItems: "Ürün Bazlı",
    custom: "Özel Tutar",
    splitCount: "Kişi Sayısı",
    selectItemsHint: "Toplamı hesaplamak için soldaki listeden ürünleri seçin.",
    fullPayment: "TAM ÖDEME",
    splitPayment: "BÖL / KISMİ",
    adjustments: "Düzeltmeler",
    addAdjustment: "İndirim / Ek ücret ekle",
    addAdjTitle: "Düzeltme Ekle",
    extraCharge: "Ek Ücret",
    discount: "İndirim",
    description: "Açıklama",
    descPlaceholder: "Örn. Servis Ücreti",
    amountLabel: "Tutar",
    applyAdjustment: "Düzeltmeyi Uygula",
    paid: "Ödendi",
    remainingDue: "Kalan Tutar",
    orderDetails: "Sipariş Detayları",
    fillAllFields: "Lütfen tüm alanları doldurun",
    adjAdded: "Düzeltme Eklendi",
    // Toasts & Alerts
    menuLoadFailed: "Menü yüklenemedi",
    addedToOrder: "Siparişe Eklendi",
    removedFromOrder: "Siparişten Çıkarıldı",
    nothingToSend: "Gönderilecek bir şey yok",
    sentToKitchen: "Mutfağa Gönderildi! 👨‍🍳",
    sentToCashier: "Onay için Kasaya Gönderildi! ⏳",
    ordersServed: "Siparişler Servis Edildi! ✅",
    orderUpdated: "Sipariş Güncellendi",
    tableStarted: "Masa Başlatıldı! 🟢",
    tableClosed: "Masa Kapatıldı",
    tableClosedVoided: "Masa Kapatıldı ve Siparişler İptal Edildi",
    itemVoided: "Ürün İptal Edildi",
    failedToConfirm: "Onay başarısız",
    failedToSend: "Gönderilemedi",
    failedToStart: "Başlatılamadı",
    failedToUpdate: "Güncellenemedi",
    failedToDelete: "Silinemedi",
    checkoutFailed: "Ödeme Başarısız",
    somethingWentWrong: "Bir şeyler ters gitti.",
    requestSent: "İstek Gönderildi!",
    billSent: "Hesap İsteği Gönderildi!",
    waiterSent: "Garson Çağrısı Gönderildi!",
    // Waiter & Statuses
    activeTables: "Aktif Masalar",
    smartSort: "Akıllı Sırala",
    numericSort: "123 Sırala",
    floorOverview: "Kat Görünümü",
    logoutConfirm: "Çıkış yapmak istediğinize emin misiniz?",
    transferring: "Transfer Ediliyor",
    selectTargetTable: "Hedef Masayı Seç",
    clickToMove: "Taşımak veya Birleştirmek için bir masaya tıklayın",
    transferCancelled: "Transfer iptal edildi",
    mergeSuccess: "Masalar başarıyla birleştirildi!",
    moveSuccess: "Masa başarıyla taşındı!",
    cannotTransferSelf: "Kendisine transfer edilemez!",
    sourceNoSession: "Kaynak masada aktif oturum yok!",
    mergeFailed: "Birleştirme başarısız",
    moveFailed: "Taşıma başarısız",
    requestCleared: "İstek Temizlendi",
    loadingFloor: "KAT YÜKLENİYOR...",
    waiterDisabled: "Garson Modülü Devre Dışı",
    moduleOff: "Bu modül şu anda kapalı.",
    // Table Status Labels
    statusEmpty: "Boş",
    statusSeated: "Oturan Var",
    statusDining: "Yemek Yeniyor",
    statusCooking: "PİŞİRİLİYOR",
    statusWaiting: "BEKLİYOR",
    statusNewOrder: "YENİ SİPARİŞ",
    statusKitchenSent: "MUTFAĞA İLETİLDİ",
    statusBillRequest: "HESAP İSTEĞİ",
    statusCalling: "ÇAĞIRIYOR!",
    statusAlert: "UYARI",
    statusMergeHere: "BURAYA BİRLEŞTİR",
    statusMoveHere: "BURAYA TAŞI",
    statusSource: "Kaynak",
    orderNote: "Sipariş Notu",
    notePlaceholder: "Alerjiler, ekstra acı vb...",
  },
  ru: {
    addToCart: "В корзину",
    addToOrder: "Добавить в заказ",
    total: "Итого",
    viewCart: "Корзина",
    empty: "Нет товаров",
    currency: "₺",
    offers: "Специальные",
    yourOrder: "Ваш заказ",
    table: "Стол",
    active: "Активен",
    emptyCart: "Корзина пуста",
    newItems: "Новые товары (Не отправлено)",
    remove: "Удалить",
    sentToKitchen: "Отправлено на кухню",
    totalAmount: "Общая сумма",
    confirmOrder: "Подтвердить заказ",
    items: "Товары",
    noNewItems: "Нет новых товаров",
    showOnTable: "Показать на столе",
    "3d": "3D",
    viewInAR: "Просмотр в AR",
    close: "Закрыть",
    yourSelection: "Ваш выбор",
    readyToOrder: "Готово к заказу",
    kitchenPreparing: "Кухня готовит",
    grandTotal: "Итого",
    yourBag: "Ваша корзина",
    emptyBag: "Пустая корзина",
    qty: "Кол-во",
    checkout: "Оформить",
    exploreMenu: "Изучить меню",
    fineDining: "Изысканная кухня",
    viewMenu: "Посмотреть меню",
    viewFullMenu: "Полное меню",
    totalOrder: "Общий заказ",
    open: "Открыто",
    enterMenu: "Войти в меню",
    menuCategories: "Категории",
    swipe: "Листайте",
    off: "СКИДКА",
    // Cashier
    swipeToDelete: "Смахните для удаления",
    floorManager: "Управление залом",
    editMode: "РЕЖИМ РЕДАКТИРОВАНИЯ",
    systemOnline: "Система онлайн",
    offline: "Офлайн",
    occupied: "Занято",
    addTable: "Добавить стол",
    woodParquet: "Паркет",
    concrete: "Бетон",
    whiteMarble: "Белый мрамор",
    terrazzo: "Терраццо",
    black: "Черный",
    resetSort: "Сбросить сорт.",
    cancel: "Отмена",
    save: "Сохранить",
    dragTables: "Перетащите столы",
    resizeTables: "Потяните за края для изменения",
    selectTargetTable: "Выберите целевой стол",
    clickToMove: "Нажмите на стол для перемещения",
    transferCancelled: "Перевод отменен",
    mergeSuccess: "Столы объединены!",
    moveSuccess: "Стол перемещен!",
    editFloor: "Редактировать зал",
    // Analytics & Reports
    analytics: "Аналитика",
    reports: "Отчеты",
    financialReports: "Финансовые отчеты",
    detailedBreakdown: "Подробный отчет за",
    totalRevenue: "Общая выручка",
    totalDishOrdered: "Всего блюд",
    totalCustomer: "Всего клиентов",
    grossSales: "Валовые продажи",
    netCash: "Наличные (Нетто)",
    netCard: "Карта (Нетто)",
    voidedValue: "Сумма отмен",
    extraCharges: "Доп. сборы",
    totalDiscounts: "Скидки",
    transactionalReport: "Отчет о транзакциях",
    productMix: "Ассортимент",
    securityLog: "Журнал безопасности",
    today: "Сегодня",
    week: "Неделя",
    month: "Месяц",
    threeMonths: "3 Месяца",
    year: "Год",
    // Waiter
    floorOverview: "Обзор зала",
    logout: "Выйти",
    transferring: "Перенос",
    selectTargetTable: "Выберите цель",
    live: "Онлайн",
    toConfirm: "Подтвердить",
    noTables: "Нет столов",
    requests: "Запросы",
    // Chef
    kitchenDisplay: "КУХОННЫЙ ЭКРАН",
    activeTickets: "Активные билеты",
    allClear: "Все чисто, Шеф!",
    noActiveOrders: "Нет активных заказов.",
    // Report Columns
    billId: "ID Чека",
    method: "Метод",
    staff: "Сотрудник",
    productName: "Название",
    quantitySold: "Продано",
    reason: "Причина",
    // Order Drawer
    closed: "Закрыто",
    add: "ДОБАВИТЬ",
    transferTable: "Перенести стол",
    closeTable: "Закрыть стол",
    editingNote: "Редактировать",
    saving: "Сохранение...",
    tableNote: "Заметка стола",
    noNotes: "Нет заметок.",
    addNotePlaceholder: "Добавить заметку...",
    totalBill: "Итоговый счет",
    finishCheckout: "ЗАВЕРШИТЬ И ОПЛАТИТЬ",
    processing: "ОБРАБОТКА...",
    tableEmpty: "Стол пуст",
    noActiveSession: "Нет активной сессии.",
    startSession: "НАЧАТЬ НОВУЮ СЕССИЮ",
    printBill: "Печать счета",
    newOrders: "Новые заказы",
    newOrderCashier: "Новый заказ (Касса)",
    confirmSendCashier: "ПОДТВЕРДИТЬ И ОТПРАВИТЬ НА КАССУ",
    confirmSendKitchen: "ПОДТВЕРДИТЬ И ОТПРАВИТЬ НА КУХНЮ",
    confirmServe: "ПОДТВЕРДИТЬ И ПОДАТЬ",
    sendKitchen: "ОТПРАВИТЬ НА КУХНЮ",
    markServed: "ОТМЕТИТЬ КАК ПОДАНО",
    startPreparing: "НАЧАТЬ ГОТОВКУ",
    served: "Подано",
    inKitchen: "На кухне / Готовится",
    updating: "ОБНОВЛЕНИЕ...",
    saveChanges: "Сохранить",
    edit: "Изменить",
    readyForPrep: "Готово к готовке",
    sentToKitchen: "Отправлено на кухню",
    callWaiter: "Позвать официанта",
    requestBill: "Попросить счет",
    // Transaction Modal
    transactionDetails: "Детали транзакции",
    id: "ID",
    loadingDetails: "Загрузка...",
    failedToLoadDetails: "Ошибка загрузки.",
    itemsInSession: "Товары в сессии",
    partialPayment: "Частичная оплата",
    noItemsFound: "Товары не найдены.",
    noImg: "Без фото",
    billAdjustments: "Корректировки счета",
    itemsTotal: "Итого товары",
    billTotal: "Итого счет",
    paidThisTransaction: "Оплачено (Эта транзакция)",
    totalPaid: "Всего оплачено",
    qtyLabel: "Кол-во",
    sessionNote: "Заметка сессии",
    // Reports & Dashboard
    hourlyTraffic: "Почасовой трафик",
    salesByCategory: "Продажи по категориям",
    mostOrdered: "Самые заказываемые",
    viewAll: "Посмотреть все",
    viewLess: "Показа меньше",
    smartSort: "Умная сортировка",
    numericSort: "123 Сортировка",
    kitchenStatus: "Кухня",
    orders: "Заказы",
    peakHours: "Пиковые часы",
    dishesOrdered: "заказанных блюд",
    today: "Сегодня",
    orderNote: "Заметка к заказу",
    notePlaceholder: "Аллергии, поострее и т.д...",
    // Payment Modal
    sendToKitchen: "Отправить на кухню",
    itemsSelected: "выбрано товаров",
    people: "Человек",
    payNow: "К оплате сейчас",
    allPrepared: "ВСЕ ГОТОВО",
    selectPaymentMethod: "Выберите метод оплаты",
    cash: "НАЛИЧНЫЕ",
    card: "КАРТА",
    mixed: "СМЕШАННЫЙ",
    cashPortion: "Наличные",
    cardPortion: "Карта",
    autofill: "Заполнить остаток",
    confirmPayment: "Подтвердить оплату",
    paymentRecorded: "Оплата записана",
    paymentFailed: "Ошибка оплаты",
    mixedMismatch: "Сумма должна быть равна к оплате",
    invalidAmount: "Неверная сумма",
    amountExceeds: "Сумма превышает остаток",
    splitMode: "Режим разделения",
    byPeople: "По людям",
    byItems: "По товарам",
    custom: "Произвольно",
    splitCount: "Кол-во людей",
    selectItemsHint: "Выберите товары из списка слева для расчета.",
    fullPayment: "ПОЛНАЯ ОПЛАТА",
    splitPayment: "РАЗДЕЛИТЬ / ЧАСТИЧНО",
    adjustments: "Корректировки",
    addAdjustment: "Проценты / Скидка",
    addAdjTitle: "Добавить корр.",
    extraCharge: "Доп. плата",
    discount: "Скидка",
    description: "Описание",
    descPlaceholder: "Напр. Сервисный сбор",
    amountLabel: "Сумма",
    applyAdjustment: "Применить",
    paid: "Оплачено",
    remainingDue: "Осталось",
    orderDetails: "Детали заказа",
    fillAllFields: "Заполните все поля",
    adjAdded: "Добавлено",
    // Toasts & Alerts
    menuLoadFailed: "Не удалось загрузить меню",
    addedToOrder: "Добавлено в заказ",
    removedFromOrder: "Удалено из заказа",
    nothingToSend: "Нечего отправлять",
    sentToKitchen: "Отправлено на кухню! 👨‍🍳",
    sentToCashier: "Отправлено на кассу для подтверждения! ⏳",
    ordersServed: "Заказы поданы! ✅",
    orderUpdated: "Заказ обновлен",
    tableStarted: "Стол запущен! 🟢",
    tableClosed: "Стол закрыт",
    tableClosedVoided: "Стол закрыт и заказы аннулированы",
    itemVoided: "Товар аннулирован",
    failedToConfirm: "Не удалось подтвердить",
    failedToSend: "Не удалось отправить",
    failedToStart: "Не удалось запустить",
    failedToUpdate: "Не удалось обновить",
    failedToDelete: "Не удалось удалить",
    checkoutFailed: "Оплата не прошла",
    somethingWentWrong: "Что-то пошло не так.",
    requestSent: "Запрос отправлен!",
    billSent: "Запрос счета отправлен!",
    waiterSent: "Вызов официанта отправлен!",
    // Waiter & Statuses
    activeTables: "Активные столы",
    smartSort: "Умная сортировка",
    numericSort: "123 Сортировка",
    floorOverview: "Обзор зала",
    logoutConfirm: "Вы уверены, что хотите выйти?",
    transferring: "Перенос",
    selectTargetTable: "Выберите цель",
    clickToMove: "Нажмите на стол для перемещения",
    transferCancelled: "Перевод отменен",
    mergeSuccess: "Столы объединены!",
    moveSuccess: "Стол перемещен!",
    cannotTransferSelf: "Нельзя перевести на себя!",
    sourceNoSession: "У стола нет активной сессии!",
    mergeFailed: "Объединение не удалось",
    moveFailed: "Перемещение не удалось",
    requestCleared: "Запрос очищен",
    loadingFloor: "ЗАГРУЗКА ЗАЛА...",
    waiterDisabled: "Модуль отключен",
    moduleOff: "Этот модуль сейчас выключен.",
    // Table Status Labels
    statusEmpty: "Пуст",
    statusSeated: "Занят",
    statusDining: "Обедают",
    statusCooking: "ГОТОВИТСЯ",
    statusWaiting: "ОЖИДАНИЕ",
    statusNewOrder: "НОВЫЙ ЗАКАЗ",
    statusKitchenSent: "НА КУХНЕ",
    statusBillRequest: "СЧЕТ",
    statusCalling: "ЗОВЕТ!",
    statusAlert: "ТРЕВОГА",
    statusMergeHere: "ОБЪЕДИНИТЬ СЮДА",
    statusMoveHere: "ПЕРЕМЕСТИТЬ СЮДА",
    statusSource: "Источник",
    orderNote: "Заметка к заказу",
    notePlaceholder: "Аллергии, поострее и т.д...",

  },
  fa: {
    addToCart: "افزودن به سبد",
    addToOrder: "افزودن به سفارش",
    total: "جمع کل",
    viewCart: "مشاهده سبد",
    empty: "موردی یافت نشد",
    currency: "لیر",
    offers: "پیشنهادات",
    yourOrder: "سفارش شما",
    table: "میز",
    active: "فعال",
    emptyCart: "سبد خرید خالی است",
    newItems: "موارد جدید (ارسال نشده)",
    remove: "حذف",
    sentToKitchen: "به آشپزخانه ارسال شد",
    totalAmount: "مبلغ کل",
    confirmOrder: "تایید سفارش",
    items: "مورد",
    noNewItems: "مورد جدیدی برای سفارش نیست",
    showOnTable: "نمایش روی میز",
    "3d": "سه‌بعدی",
    viewInAR: "مشاهده در AR",
    close: "بستن",
    yourSelection: "انتخاب‌های شما",
    readyToOrder: "آماده سفارش",
    kitchenPreparing: "آشپزخانه در حال آماده‌سازی",
    grandTotal: "جمع کل",
    yourBag: "کیف شما",
    emptyBag: "کیف خالی",
    qty: "تعداد",
    checkout: "پرداخت",
    exploreMenu: "مشاهده منو",
    fineDining: "تجربه غذای عالی",
    viewMenu: "مشاهده منو",
    viewFullMenu: "مشاهده منوی کامل",
    totalOrder: "کل سفارش",
    open: "باز",
    enterMenu: "ورود به منو",
    menuCategories: "دسته‌بندی‌ها",
    swipe: "بکشید",
    off: "تخفیف",
    // Cashier
    swipeToDelete: "برای حذف بکشید",
    floorManager: "مدیریت سالن",
    editMode: "حالت ویرایش",
    systemOnline: "سیستم آنلاین",
    offline: "آفلاین",
    occupied: "اشغال",
    addTable: "افزودن میز",
    woodParquet: "پارکت چوبی",
    concrete: "بتن",
    whiteMarble: "مرمر سفید",
    terrazzo: "ترازو",
    black: "مشکی",
    resetSort: "بازنشانی ترتیب",
    cancel: "لغو",
    save: "ذخیره",
    dragTables: "میزها را بکشید",
    resizeTables: "برای تغییر اندازه بکشید",
    selectTargetTable: "میز مقصد را انتخاب کنید",
    clickToMove: "برای انتقال یا ادغام روی میز کلیک کنید",
    transferCancelled: "انتقال لغو شد",
    mergeSuccess: "میزها با موفقیت ادغام شدند!",
    moveSuccess: "میز با موفقیت جابجا شد!",
    editFloor: "ویرایش سالن",
    // Analytics & Reports
    analytics: "آمار و تحلیل",
    reports: "گزارش‌ها",
    financialReports: "گزارش‌های مالی و امنیتی",
    detailedBreakdown: "جزئیات مربوط به",
    totalRevenue: "درآمد کل",
    totalDishOrdered: "کل غذاهای سفارش داده شده",
    totalCustomer: "تعداد مشتریان",
    grossSales: "فروش ناخالص",
    netCash: "خالص نقد",
    netCard: "خالص کارت",
    voidedValue: "مبلغ باطل شده",
    extraCharges: "هزینه‌های اضافی",
    totalDiscounts: "مجموع تخفیف‌ها",
    transactionalReport: "گزارش تراکنش‌ها",
    productMix: "ترکیب محصول",
    securityLog: "گزارش امنیتی",
    today: "امروز",
    week: "هفته",
    month: "ماه",
    threeMonths: "۳ ماه",
    year: "سال",
    // Waiter
    floorOverview: "نمای سالن",
    logout: "خروج",
    transferring: "در حال انتقال",
    selectTargetTable: "انتخاب میز مقصد",
    live: "زنده",
    toConfirm: "تایید نشده",
    noTables: "میزی پیدا نشد",
    requests: "درخواست‌ها",
    // Chef
    kitchenDisplay: "نمایشگر آشپزخانه",
    activeTickets: "تیکت‌های فعال",
    allClear: "همه چیز آماده است، سرآشپز!",
    noActiveOrders: "سفارش فعالی وجود ندارد.",
    // Report Columns
    billId: "شناسه صورتحساب",
    method: "روش",
    staff: "کارکنان",
    productName: "نام محصول",
    quantitySold: "تعداد فروخته شده",
    reason: "دلیل",
    // Order Drawer
    closed: "بسته",
    add: "افزودن",
    transferTable: "انتقال میز",
    closeTable: "بستن میز",
    editingNote: "ویرایش یادداشت",
    saving: "در حال ذخیره...",
    tableNote: "یادداشت میز",
    noNotes: "یادداشتی اضافه نشده.",
    addNotePlaceholder: "یادداشتی برای این میز بنویسید...",
    totalBill: "صورتحساب کل",
    finishCheckout: "اتمام و پرداخت",
    processing: "در حال پردازش...",
    tableEmpty: "میز خالی است",
    noActiveSession: "نشست فعالی یافت نشد.",
    startSession: "شروع نشست جدید",
    printBill: "چاپ صورتحساب",
    newOrders: "سفارشات جدید",
    newOrderCashier: "سفارش جدید (صندوقدار)",
    confirmSendCashier: "تایید و ارسال به صندوق",
    confirmSendKitchen: "تایید و ارسال به آشپزخانه",
    confirmServe: "تایید و سرو",
    sendKitchen: "ارسال به آشپزخانه",
    markServed: "علامت‌گذاری به عنوان سرو شده",
    startPreparing: "شروع آماده‌سازی",
    served: "سرو شده",
    inKitchen: "در آشپزخانه / در حال پخت",
    updating: "در حال بروزرسانی...",
    saveChanges: "ذخیره تغییرات",
    edit: "ویرایش",
    readyForPrep: "آماده برای پخت",
    sentToKitchen: "ارسال شده به آشپزخانه",
    callWaiter: "فراخوانی گارسون",
    requestBill: "درخواست صورتحساب",
    // Transaction Modal
    transactionDetails: "جزئیات تراکنش",
    id: "شناسه",
    loadingDetails: "در حال بارگذاری جزئیات...",
    failedToLoadDetails: "بارگذاری جزئیات ناموفق بود.",
    itemsInSession: "موارد موجود در نشست",
    partialPayment: "پرداخت جزئی",
    noItemsFound: "موردی یافت نشد.",
    noImg: "بدون تصویر",
    billAdjustments: "تعدیلات صورتحساب",
    itemsTotal: "مجموع موارد",
    billTotal: "جمع کل صورتحساب",
    paidThisTransaction: "پرداخت شده (این تراکنش)",
    totalPaid: "مجموع پرداختی",
    qtyLabel: "تعداد",
    sessionNote: "یادداشت نشست",
    orderNote: "یادداشت سفارش",
    notePlaceholder: "آلرژی، تندتر و غیره...",
    // Payment Modal
    sendToKitchen: "ارسال به آشپزخانه",
    itemsSelected: "مورد انتخاب شد",
    people: "نفر",
    payNow: "مبلغ قابل پرداخت",
    allPrepared: "همه آماده",
    selectPaymentMethod: "انتخاب روش پرداخت",
    cash: "نقد",
    card: "کارت",
    mixed: "ترکیبی",
    cashPortion: "بخش نقد",
    cardPortion: "بخش کارت",
    autofill: "تکمیل باقی‌مانده",
    confirmPayment: "تایید پرداخت",
    paymentRecorded: "پرداخت ثبت شد",
    paymentFailed: "پرداخت ناموفق بود",
    mixedMismatch: "مبالغ ترکیبی باید برابر با مبلغ قابل پرداخت باشد",
    invalidAmount: "مبلغ نامعتبر است",
    amountExceeds: "مبلغ بیشتر از باقی‌مانده است",
    splitMode: "حالت تقسیم",
    byPeople: "بر اساس نفرات",
    byItems: "بر اساس اقلام",
    custom: "دستی",
    splitCount: "تعداد نفرات",
    selectItemsHint: "موارد را از لیست سمت راست انتخاب کنید تا مجموع محاسبه شود.",
    fullPayment: "پرداخت کامل",
    splitPayment: "تقسیم / جزئی",
    adjustments: "تعدیلات",
    addAdjustment: "افزودن تخفیف / شارژ",
    addAdjTitle: "افزودن تعدیل",
    extraCharge: "شارژ اضافی",
    discount: "تخفیف",
    description: "توضیحات",
    descPlaceholder: "مثلاً حق سرویس",
    amountLabel: "مبلغ",
    applyAdjustment: "اعمال تعدیل",
    paid: "پرداخت شده",
    remainingDue: "باقی‌مانده",
    orderDetails: "جزئیات سفارش",
    fillAllFields: "لطفاً همه فیلدها را پر کنید",
    adjAdded: "تعدیل اضافه شد",
    // Toasts & Alerts
    menuLoadFailed: "بارگذاری منو ناموفق بود",
    addedToOrder: "به سفارش اضافه شد",
    removedFromOrder: "از سفارش حذف شد",
    nothingToSend: "چیزی برای ارسال نیست",
    sentToKitchen: "به آشپزخانه ارسال شد! 👨‍🍳",
    sentToCashier: "برای تایید به صندوق ارسال شد! ⏳",
    ordersServed: "سفارشات سرو شد! ✅",
    orderUpdated: "سفارش بروز شد",
    tableStarted: "میز شروع شد! 🟢",
    tableClosed: "میز بسته شد",
    tableClosedVoided: "میز بسته شد و سفارشات لغو شد",
    itemVoided: "مورد لغو شد",
    failedToConfirm: "تایید ناموفق",
    failedToSend: "ارسال ناموفق",
    failedToStart: "شروع ناموفق",
    failedToUpdate: "بروزرسانی ناموفق",
    failedToDelete: "حذف ناموفق",
    checkoutFailed: "پرداخت ناموفق",
    somethingWentWrong: "مشکلی پیش آمد.",
    requestSent: "درخواست ارسال شد!",
    billSent: "درخواست صورتحساب ارسال شد!",
    waiterSent: "فراخوانی گارسون ارسال شد!",
    // Waiter & Statuses
    activeTables: "میزهای فعال",
    smartSort: "مرتب‌سازی هوشمند",
    numericSort: "مرتب‌سازی عددی",
    floorOverview: "نمای سالن",
    logoutConfirm: "آیا مطمئن هستید که می‌خواهید خارج شوید؟",
    transferring: "در حال انتقال",
    selectTargetTable: "انتخاب میز مقصد",
    clickToMove: "برای انتقال یا ادغام روی میز کلیک کنید",
    transferCancelled: "انتقال لغو شد",
    mergeSuccess: "میزها با موفقیت ادغام شدند!",
    moveSuccess: "میز با موفقیت جابجا شد!",
    cannotTransferSelf: "انتقال به خود امکان‌پذیر نیست!",
    sourceNoSession: "میز مبدا نشست فعالی ندارد!",
    mergeFailed: "ادغام ناموفق",
    moveFailed: "جابجایی ناموفق",
    requestCleared: "درخواست پاک شد",
    loadingFloor: "در حال بارگذاری سالن...",
    waiterDisabled: "برنامه گارسون غیرفعال است",
    moduleOff: "این ماژول در حال حاضر خاموش است.",
    // Table Status Labels
    statusEmpty: "خالی",
    statusSeated: "نشسته",
    statusDining: "در حال غذا خوردن",
    statusCooking: "در حال پخت",
    statusWaiting: "در انتظار",
    statusNewOrder: "سفارش جدید",
    statusKitchenSent: "ارسال به آشپزخانه",
    statusBillRequest: "درخواست صورتحساب",
    statusCalling: "فراخوانی!",
    statusAlert: "هشدار",
    statusMergeHere: "ادغام در اینجا",
    statusMoveHere: "انتقال به اینجا",
    statusSource: "مبدا",
    orderNote: "یادداشت سفارش",
    notePlaceholder: "آلرژی، تندتر و غیره...",
  },
  ar: {
    addToCart: "أضف للسلة",
    addToOrder: "أضف للطلب",
    total: "المجموع",
    viewCart: "عرض السلة",
    empty: "لا يوجد عناصر",
    currency: "₺",
    offers: "عروض",
    yourOrder: "طلبك",
    table: "طاولة",
    active: "نشط",
    emptyCart: "سلتك فارغة",
    newItems: "عناصر جديدة (لم ترسل)",
    remove: "إزالة",
    sentToKitchen: "أرسل للمطبخ",
    totalAmount: "المبلغ الإجمالي",
    confirmOrder: "تأكيد الطلب",
    items: "عناصر",
    noNewItems: "لا توجد عناصر جديدة",
    showOnTable: "عرض على الطاولة",
    "3d": "ثلاثي الأبعاد",
    viewInAR: "عرض في AR",
    close: "إغلاق",
    yourSelection: "اختيارك",
    readyToOrder: "جاهز للطلب",
    kitchenPreparing: "المطبخ يحضر",
    grandTotal: "الإجمالي الكلي",
    yourBag: "حقيبتك",
    emptyBag: "حقيبة فارغة",
    qty: "الكمية",
    checkout: "الدفع",
    exploreMenu: "استكشف القائمة",
    fineDining: "تجربة طعام راقية",
    viewMenu: "عرض القائمة",
    viewFullMenu: "عرض القائمة الكاملة",
    totalOrder: "إجمالي الطلب",
    open: "مفتوح",
    enterMenu: "ادخل القائمة",
    menuCategories: "الفئات",
    swipe: "اسحب",
    off: "خصم",
    // Cashier
    swipeToDelete: "اسحب للحذف",
    floorManager: "مدير الصالة",
    editMode: "وضع التعديل",
    systemOnline: "النظام متصل",
    offline: "غير متصل",
    occupied: "مشغول",
    addTable: "إضافة طاولة",
    woodParquet: "باركيه خشبي",
    concrete: "خرسانة",
    whiteMarble: "رخام أبيض",
    terrazzo: "تيرازو",
    black: "أسود",
    resetSort: "إعادة تعيين الترتيب",
    cancel: "إلغاء",
    save: "حفظ",
    dragTables: "اسحب الطاولات للتحريك",
    resizeTables: "اسحب المقابض لتغيير الحجم",
    selectTargetTable: "اختر الطاولة المستهدفة",
    clickToMove: "انقر على أي طاولة للنقل أو الدمj",
    transferCancelled: "تم إلغاء النقل",
    mergeSuccess: "تم دمج الطاولات بنجاح!",
    moveSuccess: "تم نقل الطاولة بنجاح!",
    editFloor: "تعديل الصالة",
    // Analytics & Reports
    analytics: "تحليلات",
    reports: "تقارير",
    financialReports: "التقارير المالية والأمنية",
    detailedBreakdown: "تفاصيل لـ",
    totalRevenue: "إجمالي الإيرادات",
    totalDishOrdered: "إجمالي الأطباق المطلوبة",
    totalCustomer: "إجمالي العملاء",
    grossSales: "إجمالي المبيعات",
    netCash: "صافي النقد",
    netCard: "صافي البطاقة",
    voidedValue: "القيمة الملغاة",
    extraCharges: "رسوم إضافية",
    totalDiscounts: "إجمالي الخصومات",
    transactionalReport: "تقرير المعاملات",
    productMix: "مزيج المنتجات",
    securityLog: "سجل الأمان",
    today: "اليوم",
    week: "أسبوع",
    month: "شهر",
    threeMonths: "3 أشهر",
    year: "سنة",
    // Waiter
    floorOverview: "نظرة عامة",
    logout: "خروج",
    transferring: "جار النقل",
    selectTargetTable: "اختر الطاولة",
    live: "مباشر",
    toConfirm: "للتأكيد",
    noTables: "لا توجد طاولات",
    requests: "طلبات",
    // Chef
    kitchenDisplay: "شاشة المطبخ",
    activeTickets: "تذاكر نشطة",
    allClear: "كل شيء جاهز يا شيف!",
    noActiveOrders: "لا توجد طلبات نشطة.",
    // Report Columns
    billId: "رقم الفاتورة",
    method: "طريقة",
    staff: "الموظف",
    productName: "اسم المنتج",
    quantitySold: "الكمية المباعة",
    reason: "السبب",
    // Order Drawer
    closed: "مغلق",
    add: "إضافة",
    transferTable: "نقل الطاولة",
    closeTable: "إغلاق الطاولة",
    editingNote: "تعديل الملاحظة",
    saving: "جاري الحفظ...",
    tableNote: "ملاحظة الطاولة",
    noNotes: "لا توجد ملاحظات.",
    addNotePlaceholder: "أضف ملاحظة لهذه الطاولة...",
    totalBill: "إجمالي الفاتورة",
    finishCheckout: "إنهاء ودفع",
    processing: "جاري المعالجة...",
    tableEmpty: "الطاولة فارغة",
    noActiveSession: "لا توجد جلسة نشطة.",
    startSession: "بدء جلسة جديدة",
    printBill: "طباعة الفاتورة",
    newOrders: "طلبات جديدة",
    newOrderCashier: "طلب جديد (كاشير)",
    confirmSendCashier: "تأكيد وإرسال للكاشير",
    confirmSendKitchen: "تأكيد وإرسال للمطبخ",
    confirmServe: "تأكيد وتقديم",
    sendKitchen: "إرسال للمطبخ",
    markServed: "تحديد كمقدم",
    startPreparing: "بدء التحضير",
    served: "مقدم",
    inKitchen: "في المطبخ / جار التحضير",
    updating: "جاري التحديث...",
    saveChanges: "حفظ التغييرات",
    edit: "تعديل",
    readyForPrep: "جاهز للتحضير",
    sentToKitchen: "أرسل للمطبخ",
    callWaiter: "استدعاء النادل",
    requestBill: "طلب الفاتورة",
    // Transaction Modal
    transactionDetails: "تفاصيل المعاملة",
    id: "المعرف",
    loadingDetails: "جاري تحميل التفاصيل...",
    failedToLoadDetails: "فشل تحميل التفاصيل.",
    // Payment Modal
    sendToKitchen: "أرسل للمطبخ",
    itemsSelected: "عناصر محددة",
    people: "أشخاص",
    payNow: "المبلغ للدفع الآن",
    allPrepared: "الكل جاهز",
    selectPaymentMethod: "اختر طريقة الدفع",
    cash: "نقد",
    card: "بطاقة",
    mixed: "مختلط",
    cashPortion: "جزء النقد",
    cardPortion: "جزء البطاقة",
    autofill: "إكمال الباقي",
    confirmPayment: "تأكيد الدفع",
    paymentRecorded: "تم تسجيل الدفع",
    paymentFailed: "فشل الدفع",
    mixedMismatch: "يجب أن تساوي المبالغ المختلطة المبلغ المطلوب دفعه",
    invalidAmount: "مبلغ غير صالح",
    amountExceeds: "المبلغ يتجاوز الباقي",
    splitMode: "وضع التقسيم",
    byPeople: "حسب الأشخاص",
    byItems: "حسب العناصر",
    custom: "مخصص",
    splitCount: "عدد الأشخاص",
    selectItemsHint: "اختر العناصر من القائمة لحساب المجموع.",
    fullPayment: "دفع كامل",
    splitPayment: "تقسيم / جزئي",
    adjustments: "تعديلات",
    addAdjustment: "إضافة خصم / رسوم",
    addAdjTitle: "إضافة تعديل",
    extraCharge: "رسوم إضافية",
    discount: "خصم",
    description: "الوصف",
    descPlaceholder: "مثل رسوم الخدمة",
    amountLabel: "المبلغ",
    applyAdjustment: "تطبيق التعديل",
    paid: "مدفوع",
    remainingDue: "الباقي",
    orderDetails: "تفاصيل الطلب",
    fillAllFields: "يرجى ملء جميع الحقول",
    adjAdded: "تمت إضافة التعديل",
    itemsInSession: "العناصر في الجلسة",
    partialPayment: "دفع جزئي",
    noItemsFound: "لا توجد عناصر.",
    noImg: "لا صورة",
    billAdjustments: "تعديلات الفاتورة",
    itemsTotal: "إجمالي العناصر",
    billTotal: "إجمالي الفاتورة",
    paidThisTransaction: "مدفوع (هذه المعاملة)",
    totalPaid: "مجموع المدفوع",
    orderNote: "ملاحظة الطلب",
    notePlaceholder: "حساسية، حار زيادة، إلخ...",
    qtyLabel: "الكمية",
    sessionNote: "ملاحظة الجلسة",
    // Reports & Dashboard
    hourlyTraffic: "حركة المرور بالساعة",
    salesByCategory: "المبيعات حسب الفئة",
    mostOrdered: "الأكثر طلباً",
    viewAll: "عرض الكل",
    viewLess: "عرض أقل",
    smartSort: "فرز ذكي",
    numericSort: "فرز رقمي",
    kitchenStatus: "المطبخ",
    orders: "الطلبات",
    peakHours: "ساعات الذروة",
    dishesOrdered: "أطباق مطلوبة",
    today: "اليوم",
    // Toasts & Alerts
    menuLoadFailed: "فشل تحميل القائمة",
    addedToOrder: "تمت الإضافة للطلب",
    removedFromOrder: "تمت الإزالة من الطلب",
    nothingToSend: "لا يوجد شيء للإرسال",
    sentToKitchen: "تم الإرسال للمطبخ! 👨‍🍳",
    sentToCashier: "تم الإرسال للكاشير للموافقة! ⏳",
    ordersServed: "تم تقديم الطلبات! ✅",
    orderUpdated: "تم تحديث الطلب",
    tableStarted: "تم بدء الطاولة! 🟢",
    tableClosed: "تم إغلاق الطاولة",
    tableClosedVoided: "تم إغلاق الطاولة وإلغاء الطلبات",
    itemVoided: "تم إلغاء العنصر",
    failedToConfirm: "فشل التأكيد",
    failedToSend: "فشل الإرسال",
    failedToStart: "فشل البدء",
    failedToUpdate: "فشل التحديث",
    failedToDelete: "فشل الحذف",
    checkoutFailed: "فشل الدفع",
    somethingWentWrong: "حدث خطأ ما.",
    requestSent: "تم إرسال الطلب!",
    billSent: "تم إرسال طلب الفاتورة!",
    waiterSent: "تم إرسال نداء النادل!",
    // Waiter & Statuses
    activeTables: "طاولات نشطة",
    smartSort: "فرز ذكي",
    numericSort: "فرز رقمي",
    floorOverview: "نظرة عامة",
    logoutConfirm: "هل أنت متأكد أنك تريد الخروج؟",
    transferring: "جار النقل",
    selectTargetTable: "اختر الطاولة",
    clickToMove: "انقر للتناقل أو الدمج",
    transferCancelled: "تم إلغاء النقل",
    mergeSuccess: "تم دمج الطاولات بنجاح!",
    moveSuccess: "تم نقل الطاولة بنجاح!",
    cannotTransferSelf: "لا يمكن النقل لنفس الطاولة!",
    sourceNoSession: "الطاولة المصدر ليس لها جلسة نشطة!",
    mergeFailed: "فشل الدمج",
    moveFailed: "فشل النقل",
    requestCleared: "تم مسح الطلب",
    loadingFloor: "جار تحميل الصالة...",
    waiterDisabled: "تطبيق النادل معطل",
    moduleOff: "هذه الوحدة مغلقة حالياً.",
    // Table Status Labels
    statusEmpty: "فارغ",
    statusSeated: "مشغول",
    statusDining: "تناول الطعام",
    statusCooking: "جار الطبخ",
    statusWaiting: "انتظار",
    statusNewOrder: "طلب جديد",
    statusKitchenSent: "أرسل للمطبخ",
    statusBillRequest: "طلب فاتورة",
    statusCalling: "ينادي!",
    statusAlert: "تنبيه",
    statusMergeHere: "اغمج هنا",
    statusMoveHere: "انقل هنا",
    statusSource: "المصدر",
    orderNote: "ملاحظة الطلب",
    notePlaceholder: "حساسية، حار زيادة، إلخ...",
  },
  de: {
    addToCart: "In den Warenkorb",
    addToOrder: "Zur Bestellung",
    total: "Gesamt",
    viewCart: "Warenkorb",
    empty: "Keine Artikel",
    currency: "₺",
    offers: "Angebote",
    yourOrder: "Ihre Bestellung",
    table: "Tisch",
    active: "Aktiv",
    emptyCart: "Ihr Warenkorb ist leer",
    newItems: "Neue Artikel (Nicht gesendet)",
    remove: "Entfernen",
    sentToKitchen: "An Küche gesendet",
    totalAmount: "Gesamtbetrag",
    confirmOrder: "Bestellung bestätigen",
    items: "Artikel",
    noNewItems: "Keine neuen Artikel",
    showOnTable: "Auf Tisch zeigen",
    "3d": "3D",
    viewInAR: "In AR ansehen",
    close: "Schließen",
    yourSelection: "Ihre Auswahl",
    readyToOrder: "Bereit zur Bestellung",
    kitchenPreparing: "Küche bereitet vor",
    grandTotal: "Gesamtsumme",
    yourBag: "Ihre Tasche",
    emptyBag: "Leere Tasche",
    qty: "Menge",
    checkout: "Kasse",
    exploreMenu: "Menü erkunden",
    fineDining: "Gehobene Küche",
    viewMenu: "Menü ansehen",
    viewFullMenu: "Vollständiges Menü",
    totalOrder: "Gesamtbestellung",
    open: "Geöffnet",
    enterMenu: "Menü betreten",
    menuCategories: "Kategorien",
    swipe: "Wischen",
    off: "RABATT",
    // Cashier
    floorManager: "Saalmanager",
    editMode: "BEARBEITUNGSMODUS",
    systemOnline: "System Online",
    offline: "Offline",
    occupied: "Belegt",
    addTable: "Tisch hinzufügen",
    woodParquet: "Holzparkett",
    concrete: "Beton",
    whiteMarble: "Weißer Marmor",
    terrazzo: "Terrazzo",
    black: "Schwarz",
    resetSort: "Sortierung zurücksetzen",
    cancel: "Abbrechen",
    save: "Speichern",
    dragTables: "Tische zum Bewegen ziehen",
    resizeTables: "Griffe zum Ändern der Größe ziehen",
    selectTargetTable: "Zieltisch auswählen",
    clickToMove: "Klicken zum Verschieben/Zusammenführen",
    transferCancelled: "Übertragung abgebrochen",
    mergeSuccess: "Tische erfolgreich zusammengeführt!",
    moveSuccess: "Tisch erfolgreich verschoben!",
    editFloor: "Saal bearbeiten",
    // Analytics & Reports
    analytics: "Analytik",
    reports: "Berichte",
    financialReports: "Finanz- & Sicherheitsberichte",
    detailedBreakdown: "Detaillierte Aufschlüsselung für",
    totalRevenue: "Gesamtumsatz",
    totalDishOrdered: "Bestellte Gerichte",
    totalCustomer: "Gesamtkunden",
    grossSales: "Bruttoumsatz",
    netCash: "Netto Bar",
    netCard: "Netto Karte",
    voidedValue: "Stornierter Wert",
    extraCharges: "Zusatzgebühren",
    totalDiscounts: "Gesamtrabatte",
    transactionalReport: "Transaktionsbericht",
    productMix: "Produktmix",
    securityLog: "Sicherheitsprotokoll",
    today: "Heute",
    week: "Woche",
    month: "Monat",
    threeMonths: "3 Monate",
    year: "Jahr",
    // Waiter
    callWaiter: "Kellner rufen",
    requestBill: "Rechnung anfordern",
    floorOverview: "Saalübersicht",
    logout: "Abmelden",
    transferring: "Übertragen",
    selectTargetTable: "Zieltisch wählen",
    live: "Live",
    toConfirm: "Bestätigen",
    noTables: "Keine Tische",
    requests: "Anfragen",
    // Chef
    kitchenDisplay: "KÜCHENANZEIGE",
    activeTickets: "Aktive Tickets",
    allClear: "Alles erledigt, Chef!",
    noActiveOrders: "Keine aktiven Bestellungen.",
     // Report Columns
    billId: "Rechnungs-ID",
    method: "Methode",
    staff: "Personal",
    productName: "Produktname",
    quantitySold: "Verkaufte Menge",
    reason: "Grund",
    action: "Aktion",
    // Order Drawer
    closed: "Geschlossen",
    add: "HINZUFÜGEN",
    transferTable: "Tisch übertragen",
    closeTable: "Tisch schließen",
    editingNote: "Notiz bearbeiten",
    saving: "Speichern...",
    tableNote: "Tischnotiz",
    noNotes: "Keine Notizen hinzugefügt.",
    addNotePlaceholder: "Notiz für diesen Tisch hinzufügen...",
    totalBill: "Gesamtrechnung",
    finishCheckout: "FERTIGSTELLEN & KASSE",
    processing: "VERARBEITUNG...",
    tableEmpty: "Tisch ist leer",
    noActiveSession: "Keine aktive Sitzung gefunden.",
    startSession: "NEUE SITZUNG STARTEN",
    printBill: "Rechnung drucken",
    newOrders: "Neue Bestellungen",
    newOrderCashier: "Neue Bestellung (Kassierer)",
    confirmSendCashier: "BESTÄTIGEN & AN KASSIERER SENDEN",
    confirmSendKitchen: "BESTÄTIGEN & AN KÜCHE SENDEN",
    confirmServe: "BESTÄTIGEN & SERVIEREN",
    sendKitchen: "AN KÜCHE SENDEN",
    markServed: "ALS SERVIERT MARKIEREN",
    startPreparing: "ZUBEREITUNG STARTEN",
    served: "Serviert",
    inKitchen: "In Küche / Zubereitung",
    updating: "AKTUALISIEREN...",
    saveChanges: "Änderungen speichern",
    edit: "Bearbeiten",
    readyForPrep: "Bereit zur Zubereitung",
    sentToKitchen: "An Küche gesendet",
    // Transaction Modal
    transactionDetails: "Transaktionsdetails",
    id: "ID",
    loadingDetails: "Details laden...",
    failedToLoadDetails: "Details konnten nicht geladen werden.",
    itemsInSession: "Artikel in Sitzung",
    partialPayment: "Teilzahlung",
    noItemsFound: "Keine Artikel gefunden.",
    noImg: "Kein Bild",
    billAdjustments: "Rechnungsanpassungen",
    itemsTotal: "Artikel Gesamt",
    billTotal: "Rechnungssumme",
    paidThisTransaction: "Bezahlt (Diese Transaktion)",
    totalPaid: "Gesamt bezahlt",
    qtyLabel: "Menge",
    sessionNote: "Sitzungsnotiz",
    // Reports & Dashboard
    hourlyTraffic: "Stündlicher Verkehr",
    salesByCategory: "Umsatz nach Kategorie",
    mostOrdered: "Am meisten bestellt",
    viewAll: "Alle ansehen",
    viewLess: "Weniger ansehen",
    smartSort: "Smart Sortieren",
    numericSort: "123 Sortieren",
    kitchenStatus: "Küche",
    orders: "Bestellungen",
    peakHours: "Stoßzeiten",
    dishesOrdered: "bestellte Gerichte",
    today: "Heute",
    // Toasts & Alerts
    menuLoadFailed: "Menü konnte nicht geladen werden",
    addedToOrder: "Zur Bestellung hinzugefügt",
    removedFromOrder: "Von Bestellung entfernt",
    nothingToSend: "Nichts zu senden",
    sentToKitchen: "An Küche gesendet! 👨‍🍳",
    sentToCashier: "Zur Bestätigung an Kasse gesendet! ⏳",
    ordersServed: "Bestellungen serviert! ✅",
    orderUpdated: "Bestellung aktualisiert",
    tableStarted: "Tisch gestartet! 🟢",
    tableClosed: "Tisch geschlossen",
    tableClosedVoided: "Tisch geschlossen & Bestellungen storniert",
    itemVoided: "Artikel storniert",
    failedToConfirm: "Bestätigung fehlgeschlagen",
    failedToSend: "Senden fehlgeschlagen",
    failedToStart: "Start fehlgeschlagen",
    failedToUpdate: "Aktualisierung fehlgeschlagen",
    failedToDelete: "Löschen fehlgeschlagen",
    checkoutFailed: "Kasse fehlgeschlagen",
    somethingWentWrong: "Etwas ist schief gelaufen.",
    requestSent: "Anfrage gesendet!",
    billSent: "Rechnung angefordert!",
    waiterSent: "Kellner gerufen!",
    // Waiter & Statuses
    activeTables: "Aktive Tische",
    smartSort: "Smart Sortieren",
    numericSort: "123 Sortieren",
    floorOverview: "Übersicht",
    logoutConfirm: "Möchten Sie sich wirklich abmelden?",
    transferring: "Übertragen",
    selectTargetTable: "Zieltisch wählen",
    clickToMove: "Tisch zum Verschieben/Zusammenführen klicken",
    transferCancelled: "Übertragung abgebrochen",
    mergeSuccess: "Tische erfolgreich zusammengeführt!",
    moveSuccess: "Tisch erfolgreich verschoben!",
    cannotTransferSelf: "Kann nicht an sich selbst übertragen!",
    sourceNoSession: "Quelltisch hat keine aktive Sitzung!",
    mergeFailed: "Zusammenführen fehlgeschlagen",
    moveFailed: "Verschieben fehlgeschlagen",
    requestCleared: "Anfrage gelöscht",
    loadingFloor: "SAAL WIRD GELADEN...",
    waiterDisabled: "Kellner-App deaktiviert",
    moduleOff: "Dieses Modul ist derzeit ausgeschaltet.",
    // Table Status Labels
    statusEmpty: "Leer",
    statusSeated: "Besetzt",
    statusDining: "Essen",
    statusCooking: "KOCHEN",
    statusWaiting: "WARTEN",
    statusNewOrder: "NEUE BESTELLUNG",
    statusKitchenSent: "KÜCHE GESENDET",
    statusBillRequest: "RECHNUNG",
    statusCalling: "RUFT!",
    statusAlert: "ALARM",
    statusMergeHere: "HIER ZUSAMMENFÜHREN",
    statusMoveHere: "HIERHER VERSCHIEBEN",
    statusSource: "Quelle",
    orderNote: "Bestellnotiz",
    notePlaceholder: "Allergien, extra scharf, etc...",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children, dbSettings }) => {
  const supportedCodes = dbSettings?.supported_languages || ALL_LANGUAGES.map(l => l.code);

  const availableLanguages = ALL_LANGUAGES.filter((lang) =>
    supportedCodes.includes(lang.code)
  );

  const { restaurant } = useRestaurantData();

  const [language, setLanguage] = useState(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("app-lang");
      if (saved && supportedCodes.includes(saved)) return saved;
    }
    return dbSettings?.default_language || restaurant?.default_language || "tr";
  });

  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
    localStorage.setItem("app-lang", language);

    const currentLangConfig = ALL_LANGUAGES.find((l) => l.code === language);
    const dir = currentLangConfig?.dir || "ltr";

    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, restaurant]); // Added restaurant to dependency array to re-evaluate if it loads later

  const t = (key) =>
    DICTIONARY[language]?.[key] || DICTIONARY["tr"][key] || key;

  const content = (data) => {
    if (!data) return "";
    return typeof data === "object"
      ? data[language] ||
          data[dbSettings?.default_language] ||
          data["tr"] ||
          Object.values(data)[0]
      : data;
  };

  if (!isLoaded) return null;

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        content,
        availableLanguages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
